/* qr_selftest.c - synthetic QR pattern for the capture->decode self-test.
 *
 * Generated by flux/forgebox/scripts/gen_qr_selftest.py - do not hand-edit.
 * The pattern is a valid version-1 QR (ECC level M) carrying "SELFTEST-OK".
 * drv_qrdecode.c stamps it into the completed capture buffer every few
 * frames so a decode that never happens on a real scene can be attributed:
 *   - self-test decodes  -> capture->decode path works end to end; the
 *     problem is the scene (distance / focus / framing).
 *   - self-test fails    -> pipeline problem (config / memory / flow).
 */
#include "qr_selftest.h"

/* One uint32 per row; bit (QR_SELFTEST_MODULES-1 - col) set = dark module. */
const uint32_t g_qr_selftest_modules[QR_SELFTEST_MODULES] = {
    0x01FD47F  /* row  0 */,
    0x0105541  /* row  1 */,
    0x017505D  /* row  2 */,
    0x0175E5D  /* row  3 */,
    0x0175F5D  /* row  4 */,
    0x0104441  /* row  5 */,
    0x01FD57F  /* row  6 */,
    0x0001800  /* row  7 */,
    0x00D6D5F  /* row  8 */,
    0x01F1D83  /* row  9 */,
    0x0094878  /* row 10 */,
    0x01B0D8D  /* row 11 */,
    0x01B4366  /* row 12 */,
    0x0001D6A  /* row 13 */,
    0x01FD43E  /* row 14 */,
    0x0104B50  /* row 15 */,
    0x0175067  /* row 16 */,
    0x0174EAE  /* row 17 */,
    0x0175AFD  /* row 18 */,
    0x01057A7  /* row 19 */,
    0x01FC6C1  /* row 20 */,
};

void QrSelfTestStamp(uint8_t *buf, int width, int height)
{
    const int span = (QR_SELFTEST_MODULES + 2 * QR_SELFTEST_QUIET) * QR_SELFTEST_MODULE_PX;
    const int x0 = (width - span) / 2;
    const int y0 = (height - span) / 2;

    /* Quiet zone / light background over the whole stamp area. */
    for (int y = 0; y < span; y++) {
        uint8_t *row = buf + (y0 + y) * width + x0;
        for (int x = 0; x < span; x++) {
            row[x] = QR_SELFTEST_LIGHT;
        }
    }

    for (int r = 0; r < QR_SELFTEST_MODULES; r++) {
        uint32_t bits = g_qr_selftest_modules[r];
        for (int c = 0; c < QR_SELFTEST_MODULES; c++) {
            if (bits & (1u << (QR_SELFTEST_MODULES - 1 - c))) {
                const int mx = x0 + (QR_SELFTEST_QUIET + c) * QR_SELFTEST_MODULE_PX;
                const int my = y0 + (QR_SELFTEST_QUIET + r) * QR_SELFTEST_MODULE_PX;
                for (int yy = 0; yy < QR_SELFTEST_MODULE_PX; yy++) {
                    uint8_t *row = buf + (my + yy) * width + mx;
                    for (int xx = 0; xx < QR_SELFTEST_MODULE_PX; xx++) {
                        row[xx] = QR_SELFTEST_DARK;
                    }
                }
            }
        }
    }
}
