/* shlosilo C-ABI — generated by cbindgen, do not edit by hand */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * APT 地址长度（"0x" + 64 hex = 66 字符）
 */
#define APTOS_ADDRESS_LEN 66

#define SUI_ADDRESS_LEN 66

/**
 * Arweave 地址长度（base64url 编码 512-bit SHA-256 digest = 43 字符）
 */
#define ARWEAVE_ADDRESS_MAX_LEN 64

/**
 * BTC 地址（最大 90 chars bech32 编码）
 */
#define BTC_ADDRESS_MAX_LEN 90

/**
 * P2WPKH witness program 长度（20 bytes）
 */
#define P2WPKH_WITNESS_PROGRAM_LEN 20

/**
 * P2TR witness program 长度（32 bytes x-only pubkey）
 */
#define P2TR_WITNESS_PROGRAM_LEN 32

/**
 * Cardano 地址长度（bech32，最长 ~100 字符）
 */
#define CARDANO_ADDRESS_MAX_LEN 120

/**
 * ETH 地址字符串长度（"0x" + 40 hex = 42 字符）
 */
#define ETH_ADDRESS_LEN 42

/**
 * SOL 地址长度（base58 编码 32-byte pubkey，约 32-44 字符）
 */
#define SOL_ADDRESS_MAX_LEN 64

/**
 * XMR 地址最大长度（base58 编码 69 bytes = 8-byte × 8 + 5-byte tail → 11×8 + 7 = 95 chars，< 128 安全余量）
 */
#define XMR_ADDRESS_MAX_LEN 128

/**
 * XRP 地址（classic base58 编码，最长 ~35 字符）
 */
#define XRP_ADDRESS_MAX_LEN 64

/**
 * SIGHASH 类型
 */
#define SIGHASH_ALL 1

#define UNSIGNED_TX 0

#define NON_WITNESS_UTXO 0

#define WITNESS_UTXO 1

#define PARTIAL_SIG 2

#define SIGHASH_TYPE 3

#define REDEEM_SCRIPT 4

#define WITNESS_SCRIPT 5

#define BIP32_DERIVATION 6

/**
 * Final scriptSig (for legacy P2PKH + P2SH inputs)
 */
#define FINAL_SCRIPT_SIG 7

/**
 * Final script Witness (for segwit P2WPKH/P2WSH inputs)
 */
#define FINAL_SCRIPTWITNESS 8

/**
 * 0x13: Taproot key-path signature (key = [0x13], value = 64-byte Schnorr sig)
 */
#define TAP_KEY_SIG 19

/**
 * 0x14: Taproot script-path signature (key = [0x14 || 32-byte leaf_hash], value = 64-byte Schnorr sig || 1-byte sighash)
 */
#define TAP_SCRIPT_SIG 20

/**
 * 0x15: Taproot leaf scripts (key = [0x15 || 32-byte leaf_hash], value = [script || 1-byte leaf_version])
 */
#define TAP_LEAF_SCRIPTS 21

/**
 * 0x16: Taproot BIP-32 derivation (key = [0x16 || 32-byte x-only pubkey], value = bip32 path + fingerprint)
 */
#define TAP_BIP32_DERIVATION 22

/**
 * 0x17: Taproot internal key (key = [], value = 32-byte x-only internal pubkey)
 */
#define TAP_INTERNAL_KEY 23

/**
 * 0x18: Taproot merkle root (key = [], value = 32-byte merkle root; empty = keypath-only)
 */
#define TAP_MERKLE_ROOT 24

/**
 * 0x66: Taproot tree (key = [], value = taproot tree encoding)
 */
#define TAP_TREE 102

/**
 * Witness program version (always 1 for P2TR per BIP-86)
 */
#define P2TR_WITNESS_VERSION 1

/**
 * SIGHASH 类型常量 (BIP-341)
 */
#define SIGHASH_DEFAULT 0

#define SIGHASH_NONE 2

#define SIGHASH_SINGLE 3

#define SIGHASH_ANYONECANPAY 128

/**
 * BIP-125: nSequence < 0xfffffffe 表示可替换
 */
#define RBF_THRESHOLD 4294967294

/**
 * nLockTime 高度/时间分界（BIP-65 / Bitcoin Core）
 */
#define LOCKTIME_THRESHOLD 500000000

/**
 * BIP-68 disable flag
 */
#define SEQUENCE_LOCKTIME_DISABLE_FLAG (1 << 31)

/**
 * BIP-68 type flag（set = 时间，clear = 高度）
 */
#define SEQUENCE_LOCKTIME_TYPE_FLAG (1 << 22)

/**
 * 超过此值视为「巨大」（21M BTC，单位 sat）
 */
#define MAX_MONEY_SATS (21000000 * 100000000)

/**
 * P2PKH dust
 */
#define DUST_SATS 546

/**
 * CLSAG ring 最大长度（XMR 协议默认 11 = 1 real + 10 decoys）
 */
#define DEFAULT_RING_LEN 11

/**
 * CLSAG signature 序列化长度（64 bytes）
 * 实际 monero-clsag Clsag 结构体 serialize 后长度 ≈ 64 bytes
 */
#define CLSAG_PROOF_LEN 64

/**
 * Key image 长度（32 bytes compressed）
 */
#define KEY_IMAGE_LEN 32

/**
 * Type 0: full borromean (pre-fork, deprecated)
 */
#define FULL 0

/**
 * Type 1: simple borromean (deprecated)
 */
#define SIMPLE 1

/**
 * Type 2: bulletproofs (per-output BP+ range proof)
 */
#define BULLETPROOFS 2

/**
 * Type 3: bulletproofs2 (aggregated BP+, post-fork 1788000)
 */
#define BULLETPROOFS_PLUS 3

/**
 * entropy 长度下限（misuse guard，非熵质量验证——见模块文档）。
 */
#define ENTROPY_MIN_LEN 16

/**
 * XMR tx version: 2 = RingCT (post-fork, only valid in mainnet)
 */
#define TX_VERSION 2

/**
 * Legacy (pre-RingCT, deprecated)
 */
#define TX_OUT_GEN 0

/**
 * TxOutToKey: standard stealth output (RingCT 兼容)
 */
#define TX_OUT_TO_KEY 2

/**
 * TxOutToTaggedKey: 标记密钥输出 (subaddress)
 */
#define TX_OUT_TO_TAGGED_KEY 3

/**
 * ed25519 标量长度（32 bytes）
 */
#define SCALAR_LEN SECRET_KEY_LENGTH

/**
 * ed25519 压缩点长度（32 bytes）
 */
#define COMPRESSED_POINT_LEN PUBLIC_KEY_LENGTH

/**
 * RSA-4096 签名最大长度（512 bytes for 4096-bit key + PSS overhead）
 */
#define RSA_SIGNATURE_MAX_LEN 512

/**
 * secp256k1 未压缩公钥长度（65 bytes，0x04 || X(32) || Y(32)）
 */
#define UNCOMPRESSED_POINT_LEN 65

/**
 * BIP-32 扩展私钥（78 bytes：version + depth + fp + chain_code + key + ...）
 */
#define EXTENDED_PRIVKEY_LEN 78

/**
 * BIP-67 排序的公钥列表（用于 P2SH multisig redeem script）
 */
#define MAX_MULTISIG_SIGNERS 15

#define MAX_DEPTH 16

/**
 * BIP-32 hardened bit（最高位）
 */
#define HARDENED_BIT 2147483648

/**
 * Soft index 上限（无符号 31-bit）
 */
#define MAX_SOFT_INDEX 2147483647

/**
 * SLIP-0010 扩展私钥（ed25519 比特字段不同，长度 32 bytes）
 */
#define SLIP10_EXTENDED_KEY_LEN 32

/**
 * base58check 字符串最大长度
 */
#define BASE58_MAX_LEN 128

/**
 * base64 字符串最大长度
 */
#define BASE64_MAX_LEN 256

/**
 * bech32 字符串最大长度
 */
#define BECH32_MAX_LEN 128

/**
 * Keccak-256 输出长度
 */
#define KECCAK256_OUTPUT_LEN 32

/**
 * RIPEMD-160 输出长度
 */
#define RIPEMD160_OUTPUT_LEN 20

/**
 * SHA-256 输出长度
 */
#define SHA256_OUTPUT_LEN 32

/**
 * SHA-512 输出长度
 */
#define SHA512_OUTPUT_LEN 64

/**
 * 错误码体系（2026-08-31 全量对齐 Rust `ShlosiloErrorCode` 稳定负码——单一真值源）
 *
 * 历史：0.1.x 时代只有 -1..-4 四个 define，与 R2 整改后 `to_ffi_code` 的映射码
 * 冲突（如 buffer-too-small 一度既是 -3 又是 -20）。C 宿主接入前统一收口。
 * **破坏性变更：ERR_BUFFER_TOO_SMALL 由 -3 改为 -20**（0.1.x 无宿主使用，安全）。
 */
#define ERR_UNKNOWN                -1
#define ERR_INVALID_ARGUMENT       -2
#define ERR_FFI_PANIC              -4
#define ERR_UNSUPPORTED_CHAIN      -10
#define ERR_UNSUPPORTED_EXPORT     -11
#define ERR_UNSUPPORTED_NETWORK    -12
#define ERR_MULTISIG_NOT_SUPPORTED -13
#define ERR_FEATURE_NOT_IMPL       -14
#define ERR_PSBT_OWNERSHIP         -15
#define ERR_BUFFER_TOO_SMALL       -20
#define ERR_ENCODING               -21
#define ERR_INVALID_UR_PAYLOAD     -30
#define ERR_INVALID_MNEMONIC       -31
#define ERR_INVALID_DERIVATION     -32
#define ERR_INVALID_DICE_ROLLS     -33
#define ERR_CRYPTO                 -40
#define ERR_INVARIANT              -99

/* 向后兼容别名（0.2.x 过渡，勿在新代码使用） */
#define ERR_NULL_POINTER ERR_INVALID_ARGUMENT

/**
 * 成功
 */
#define OK 0

/**
 * shlosilo 完整版本（cabi + runtime）
 */
#define SHLOSILO_VERSION_MAJOR 0

#define SHLOSILO_VERSION_MINOR 5

#define SHLOSILO_VERSION_PATCH 0

/**
 * C ABI 版本（**跟 runtime 版本独立**——L3 必须校验 ABI 版本匹配）
 *
 * ABI 版本不兼容规则：
 * - major 版本不同 → ABI 不兼容
 * - minor / patch 改变 → ABI 兼容
 */
#define SHLOSILO_CABI_VERSION_MAJOR 0

#define SHLOSILO_CABI_VERSION_MINOR 2

#define SHLOSILO_CABI_VERSION_PATCH 0

/**
 * BIP-39 seed 长度（64 bytes）
 */
#define BIP39_SEED_LEN 64

#define MAX_MNEMONIC_WORDS 24

/**
 * CLSAG 环签名（可变长度，取决于环大小）
 */
#define CLSAG_PROOF_MAX_LEN (32 * 16)

/**
 * ECDSA 签名（r, s 压缩序列化）
 *
 * 字节长度固定：32 (r) + 32 (s) = 64 bytes
 */
#define ECDSA_SIGNATURE_LEN 64

#define EDDSA_SIGNATURE_LEN 64

/**
 * FCMP++ 证明长度（待 Phase 7 实际确定）
 */
#define FCMP_PROOF_MAX_LEN 1024

/**
 * RSA-PSS 签名固定长度（512 bytes for RSA-4096）
 */
#define RSA_PSS_SIGNATURE_LEN 512

#define SCHNORR_SIGNATURE_LEN 64

/**
 * JSON 编码的 view key 字符串（Feather Wallet 兼容，最长 ~256 字符）
 */
#define JSON_MONERO_VIEWKEY_MAX_LEN 512

/**
 * 原始 payload 上限（codec 产出的 CBOR）
 */
#define UR_PAYLOAD_MAX_LEN 2048

/**
 * 完整 URI 上限：prefix + bytewords(payload+crc32) ≈ 2×payload + 头
 */
#define UR_URI_MAX_LEN 8192

/**
 * L3 提供：FreeRTOS pvPortMalloc 包装
 */
extern uint8_t *shlosilo_embedded_malloc(uintptr_t size);

/**
 * L3 提供：vPortFree 包装
 */
extern void shlosilo_embedded_free(uint8_t *ptr);

/**
 * L3 提供：panic 信息显示（LCD）+ 保持系统运行/刷新
 */
extern void shlosilo_panic_hook(const uint8_t *msg, uintptr_t len);

/**
 * shlosilo_sign_ffi — mnemonic + UR payload → 签名
 *
 * 返回 0 = Ok（长度写 *actual_len），负数 = 错误码。
 */
int shlosilo_sign_ffi(const uint16_t *mnemonic_indices,
                      int mnemonic_count,
                      const uint8_t *passphrase,
                      unsigned int passphrase_len,
                      const uint8_t *ur_payload,
                      unsigned int ur_payload_len,
                      unsigned int network,
                      uint8_t *output_buf,
                      unsigned int output_buf_len,
                      unsigned int *actual_len);

/**
 * shlosilo_sign_ur_ffi — 完整 UR 字符串 + mnemonic → 签名（P6.1d）
 *
 * L3 直接喂 `ur:crypto-psbt/...` / `ur:eth-sign-request/...` / `ur:xmr-txunsigned/...`，
 * UR 解码 + type tag 校验都在库内做（L3 薄、L1 厚）。
 *
 * **§B.5 RNG 注入扩展（2026-08-28）**：新增 entropy_ptr / entropy_len 参数——
 * XMR 签名 REQUIRED（≥16B，L3 承诺来源与 min-entropy）；BTC/ETH deterministic
 * backend 传 NULL/0 即可。同一 (keys, tx, entropy) → 同一签名（deterministic retry）。
 *
 * 返回 0 = Ok，负数 = 错误码；签名 bytes 写 output_buf。
 */
int shlosilo_sign_ur_ffi(const char *uri,
                         const uint16_t *mnemonic_indices,
                         int mnemonic_count,
                         const uint8_t *passphrase,
                         unsigned int passphrase_len,
                         unsigned int network,
                         const uint8_t *entropy_ptr,
                         unsigned int entropy_len,
                         uint8_t *output_buf,
                         unsigned int output_buf_len,
                         unsigned int *actual_len);

/**
 * shlosilo_export_readonly_ffi — mnemonic + path → 只读凭证 UR
 *
 * **P1-04（2026-08-29）**：seed 不再跨 FFI。入口收 mnemonic indices + passphrase，
 * 库内现场恢复 BIP-39 seed（栈 buffer，`SecretBytes::take` 接管清零），导出完成即弃。
 *
 * paths 为 flat u32 数组（hardened bit = 0x8000_0000），
 * `path_elem_count` 是这一个 path 的元素数（v1 单 path）。
 */
int shlosilo_export_readonly_ffi(const uint16_t *mnemonic_indices,
                                 int mnemonic_count,
                                 const uint8_t *passphrase,
                                 unsigned int passphrase_len,
                                 unsigned int network,
                                 const uint32_t *path_elems,
                                 unsigned int path_elem_count,
                                 unsigned int protocol,
                                 uint8_t *output_buf,
                                 unsigned int output_buf_len,
                                 unsigned int *actual_len);

/**
 * shlosilo_create_account_ffi — dice entropy → mnemonic(u16 LE 索引对)
 *
 * **P1-04（2026-08-29）**：`seed_out` 删除——seed 不跨 FFI（v2 安全模型）。
 * dice → mnemonic 是唯一产出；后续签名/导出直接收 mnemonic（库内现场恢复 seed）。
 * passphrase 保留（未来离线 create 时写进设备存储的元数据），当前仅做上限校验。
 */
int shlosilo_create_account_ffi(unsigned int word_count,
                                unsigned int sides,
                                const uint8_t *rolls,
                                unsigned int rolls_count,
                                const uint8_t *passphrase,
                                unsigned int passphrase_len,
                                uint8_t *mnemonic_buf,
                                unsigned int mnemonic_buf_len);

/**
 * 支持的 Network u8 列表（L3 启动时 UI dispatch 用）
 */
int shlosilo_supported_networks_ffi(uint8_t *output_buf,
                                    unsigned int output_buf_len,
                                    unsigned int *actual_len);

/**
 * 支持的 ExportProtocol u8 列表
 */
int shlosilo_supported_protocols_ffi(uint8_t *output_buf,
                                     unsigned int output_buf_len,
                                     unsigned int *actual_len);

/**
 * extern "C" 返回版本字符串（C 端 strdup 后用）
 */
const uint8_t *shlosilo_version(void);

/**
 * extern "C" 返回 C ABI 版本字符串
 */
const uint8_t *shlosilo_cabi_version(void);

/**
 * L3 启动时校验 ABI 兼容性（major 必须匹配）
 *
 * 返回 0 = ABI 兼容，非 0 = 不兼容
 */
int32_t shlosilo_cabi_check(uint16_t l3_expected_major,
                            uint16_t l3_expected_minor,
                            uint16_t l3_expected_patch);

/* ============================================================================
 * R3 typed 多分片 UR FFI（2026-08-31 定稿）
 *
 * 双通道架构（对齐 keystone gui_model.c）：
 *   单帧大 QR   = shlosilo_sign_ur_ffi / shlosilo_version 系既有入口
 *                 （payload <= UR_PAYLOAD_MAX_LEN = 2048）
 *   多分片动画  = 本组函数（payload <= 16384，fountain 冗余帧流，
 *                 帧格式 `ur:<type>/<seq>-<count>/<bytewords>`，XMR cyclic 补扫）
 *
 * 句柄契约：
 *   - encode_begin / decode_new 成功返回非 null 句柄（库内 Box 裸指针）
 *   - 句柄不可重复 free；encode_free / decode_free null 安全（幂等）
 *   - 其余函数对 null 句柄返回 ERR_INVALID_ARGUMENT
 *   - L3 缓冲区契约：frame_buf 必须 >= SHLOSILO_MULTIPART_FRAME_BUF_MAX_LEN
 * ============================================================================
 */

/** 单帧 URI 字符串缓冲下限（200B 分片 -> 帧 ~420 字符，1024 充足） */
#define SHLOSILO_MULTIPART_FRAME_BUF_MAX_LEN 1024

/** 多分片 payload 上限（对齐 TxTemplate 16 KiB） */
#define SHLOSILO_MULTIPART_PAYLOAD_MAX_LEN 16384

/** 编码器句柄（不透明；L3 不得解引用） */
typedef void shlosilo_ur_encoder_t;

/** 解码器句柄（不透明；L3 不得解引用） */

typedef void shlosilo_ur_decoder_t;

/**
 * 创建多分片编码器。
 *
 * @param type_name        UR type（ASCII 字母数字 + '-'，如 "xmr-txunsigned"，NUL 结尾，<=64）
 * @param payload          原始 payload bytes（codec 产出的 CBOR）
 * @param payload_len      <= SHLOSILO_MULTIPART_PAYLOAD_MAX_LEN
 * @param max_fragment_len 每帧 payload 分片字节数（keystone 默认 200）
 * @return 非 null = 句柄；null = 失败（参数非法 / payload 超限）。用完必须 encode_free。
 */
shlosilo_ur_encoder_t *shlosilo_ur_encode_begin(
    const char *type_name,
    const uint8_t *payload,
    unsigned int payload_len,
    unsigned int max_fragment_len);

/**
 * 取下一帧（fountain 冗余帧流，可无限调用产出新组合）。
 *
 * @return 0 = Ok（帧写入 frame_buf，NUL 结尾，长度写 *actual_len）；
 *         ERR_INVALID_ARGUMENT = null 句柄/buf；ERR_BUFFER_TOO_SMALL = buf < 下限。
 */
int shlosilo_ur_encode_next(
    shlosilo_ur_encoder_t *handle,
    uint8_t *frame_buf,
    unsigned int frame_buf_len,
    unsigned int *actual_len);

/**
 * XMR cyclic 补扫帧：seq 到顶回 1，无限循环（软件钱包补扫用）。
 * 参数与返回同 shlosilo_ur_encode_next。
 */
int shlosilo_ur_encode_next_cyclic(
    shlosilo_ur_encoder_t *handle,
    uint8_t *frame_buf,
    unsigned int frame_buf_len,
    unsigned int *actual_len);

/** 释放编码器（null 安全幂等；调用后句柄失效） */
void shlosilo_ur_encode_free(shlosilo_ur_encoder_t *handle);

/** 创建多分片解码器。非 null = 句柄；null = 失败。用完必须 decode_free。 */
shlosilo_ur_decoder_t *shlosilo_ur_decode_new(void);

/**
 * 喂一帧 URI（NUL 结尾 C string）。
 *
 * @param accepted_out 可为 null；非 null 时写 1 = 有新信息 / 0 = 重复帧
 * @return 0 = Ok；负数 = 错误码（畸形帧 = ERR_ENCODING）
 */
int shlosilo_ur_decode_feed(
    shlosilo_ur_decoder_t *handle,
    const char *frame,
    unsigned int *accepted_out);

/** 解码进度 0..=99（100 用 complete 表达）；null 句柄 = ERR_INVALID_ARGUMENT */
int shlosilo_ur_decode_progress(shlosilo_ur_decoder_t *handle);

/** 是否完成：1 = 完成，0 = 未完成 */
int shlosilo_ur_decode_complete(shlosilo_ur_decoder_t *handle);

/**
 * 取完整 payload。
 *
 * @return 0 = Ok；ERR_INVALID_ARGUMENT = null；ERR_UNKNOWN = 尚未完成；
 *         ERR_BUFFER_TOO_SMALL = buf 不足（*actual_len 写需求值）。
 */
int shlosilo_ur_decode_payload(
    shlosilo_ur_decoder_t *handle,
    uint8_t *payload_buf,
    unsigned int payload_buf_len,
    unsigned int *actual_len);

/** 释放解码器（null 安全幂等） */
void shlosilo_ur_decode_free(shlosilo_ur_decoder_t *handle);
