/* shlosilo C-ABI — generated by cbindgen, do not edit by hand */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * APT 地址长度（"0x" + 64 hex = 66 字符）
 */
#define APTOS_ADDRESS_LEN 66

#define SUI_ADDRESS_LEN 66

/**
 * Arweave 地址长度（base64url 编码 512-bit SHA-256 digest = 43 字符）
 */
#define ARWEAVE_ADDRESS_MAX_LEN 64

/**
 * BTC 地址（最大 90 chars bech32 编码）
 */
#define BTC_ADDRESS_MAX_LEN 90

/**
 * P2WPKH witness program 长度（20 bytes）
 */
#define P2WPKH_WITNESS_PROGRAM_LEN 20

/**
 * P2TR witness program 长度（32 bytes x-only pubkey）
 */
#define P2TR_WITNESS_PROGRAM_LEN 32

/**
 * Cardano 地址长度（bech32，最长 ~100 字符）
 */
#define CARDANO_ADDRESS_MAX_LEN 120

/**
 * ETH 地址字符串长度（"0x" + 40 hex = 42 字符）
 */
#define ETH_ADDRESS_LEN 42

/**
 * SOL 地址长度（base58 编码 32-byte pubkey，约 32-44 字符）
 */
#define SOL_ADDRESS_MAX_LEN 64

/**
 * XMR 地址最大长度（base58 编码 69 bytes = 8-byte × 8 + 5-byte tail → 11×8 + 7 = 95 chars，< 128 安全余量）
 */
#define XMR_ADDRESS_MAX_LEN 128

/**
 * XRP 地址（classic base58 编码，最长 ~35 字符）
 */
#define XRP_ADDRESS_MAX_LEN 64

#define UNSIGNED_TX 0

/**
 * BIP-125: nSequence < 0xfffffffe 表示可替换
 */
#define RBF_THRESHOLD 4294967294

/**
 * nLockTime 高度/时间分界（BIP-65 / Bitcoin Core）
 */
#define LOCKTIME_THRESHOLD 500000000

/**
 * BIP-68 disable flag
 */
#define SEQUENCE_LOCKTIME_DISABLE_FLAG (1 << 31)

/**
 * BIP-68 type flag（set = 时间，clear = 高度）
 */
#define SEQUENCE_LOCKTIME_TYPE_FLAG (1 << 22)

/**
 * 超过此值视为「巨大」（21M BTC，单位 sat）
 */
#define MAX_MONEY_SATS (21000000 * 100000000)

/**
 * P2PKH dust
 */
#define DUST_SATS 546

/**
 * Witness program version (always 1 for P2TR per BIP-86)
 */
#define P2TR_WITNESS_VERSION 1

/**
 * CLSAG ring 最大长度（XMR 协议默认 11 = 1 real + 10 decoys）
 */
#define DEFAULT_RING_LEN 11

/**
 * CLSAG signature 序列化长度（64 bytes）
 * 实际 monero-clsag Clsag 结构体 serialize 后长度 ≈ 64 bytes
 */
#define CLSAG_PROOF_LEN 64

/**
 * Key image 长度（32 bytes compressed）
 */
#define KEY_IMAGE_LEN 32

/**
 * key image 伴随签名的 wire：连续 `[32B image][64B signature]` 记录流，
 * 对齐 keystone `KeyImages::to_bytes` / `From<&Vec<u8>>`（96B 步长）。
 */
#define KEY_IMAGE_RECORD_LEN 96

/**
 * Type 0: full borromean (pre-fork, deprecated)
 */
#define FULL 0

/**
 * Type 1: simple borromean (deprecated)
 */
#define SIMPLE 1

/**
 * Type 2: bulletproofs (per-output BP+ range proof)
 */
#define BULLETPROOFS 2

/**
 * Type 3: bulletproofs2 (aggregated BP+, post-fork 1788000)
 */
#define BULLETPROOFS_PLUS 3

/**
 * entropy 长度下限（misuse guard，非熵质量验证——见模块文档）。
 */
#define ENTROPY_MIN_LEN 16

/**
 * XMR tx version: 2 = RingCT (post-fork, only valid in mainnet)
 */
#define TX_VERSION 2

/**
 * Legacy (pre-RingCT, deprecated)
 */
#define TX_OUT_GEN 0

/**
 * TxOutToKey: standard stealth output (RingCT 兼容)
 */
#define TX_OUT_TO_KEY 2

/**
 * TxOutToTaggedKey: 标记密钥输出 (subaddress)
 */
#define TX_OUT_TO_TAGGED_KEY 3

/**
 * RSA-4096 签名最大长度（512 bytes for 4096-bit key + PSS overhead）
 */
#define RSA_SIGNATURE_MAX_LEN 512

/**
 * secp256k1 未压缩公钥长度（65 bytes，0x04 || X(32) || Y(32)）
 */
#define UNCOMPRESSED_POINT_LEN 65

/**
 * BIP-32 扩展私钥（78 bytes：version + depth + fp + chain_code + key + ...）
 */
#define EXTENDED_PRIVKEY_LEN 78

/**
 * BIP-67 排序的公钥列表（用于 P2SH multisig redeem script）
 */
#define MAX_MULTISIG_SIGNERS 15

#define MAX_DEPTH 16

/**
 * BIP-32 hardened bit（最高位）
 */
#define HARDENED_BIT 2147483648

/**
 * Soft index 上限（无符号 31-bit）
 */
#define MAX_SOFT_INDEX 2147483647

/**
 * SLIP-0010 扩展私钥（ed25519 比特字段不同，长度 32 bytes）
 */
#define SLIP10_EXTENDED_KEY_LEN 32

/**
 * base58check 字符串最大长度
 */
#define BASE58_MAX_LEN 128

/**
 * base64 字符串最大长度
 */
#define BASE64_MAX_LEN 256

/**
 * bech32 字符串最大长度
 */
#define BECH32_MAX_LEN 128

/**
 * decoder 侧 budget（X1 纪律同源）：上限=分片数上限。
 * TxTemplate 16 KiB / 最小帧 200B → 最多 ~82 分片；256 给足裕量。
 */
#define MAX_SEQUENCE_COUNT 256

/**
 * Gate4 #4（2026-09-01 再复审）：单 session 总接收帧数预算。
 * BC-UR 允许无限冗余帧，但 decoder 资源必须有限：received(buffer/queue 同源)
 * 都以 received 集合为闸，超过此上限的会话视为异常/攻击，稳定报错。
 */
#define MAX_TOTAL_FRAMES 4096

/**
 * 审计 #5 P1-01(开-02):消元工作量预算——XOR 字节累计上限。
 * 正常重组工作量 O(count × fragment) ≈ 256 × 200B = 51KB;
 * 16MiB 上限 = 正常工作的 ~300 倍,恶意 XOR 放大攻击(大量 mixed
 * equations 反复消元)在耗尽 CPU 前先撞此墙。
 */
#define MAX_XOR_WORK_BYTES ((16 * 1024) * 1024)

/**
 * Keccak-256 输出长度
 */
#define KECCAK256_OUTPUT_LEN 32

/**
 * RIPEMD-160 输出长度
 */
#define RIPEMD160_OUTPUT_LEN 20

/**
 * SHA-256 输出长度
 */
#define SHA256_OUTPUT_LEN 32

/**
 * SHA-512 输出长度
 */
#define SHA512_OUTPUT_LEN 64

/**
 * BIP-39 seed 长度（64 bytes）
 */
#define BIP39_SEED_LEN 64

#define MAX_MNEMONIC_WORDS 24











/**
 * shlosilo 完整版本（cabi + runtime）
 */
#define SHLOSILO_VERSION_MAJOR 0

#define SHLOSILO_VERSION_MINOR 5

#define SHLOSILO_VERSION_PATCH 0

/**
 * C ABI 版本（**跟 runtime 版本独立**——L3 必须校验 ABI 版本匹配）
 *
 * ABI 版本不兼容规则（`shlosilo_cabi_check` 实现为**严格等值**）：
 * - major 不同 → -1（ABI 不兼容，签名/错误码布局变更）
 * - minor 不同 → -2（导出函数集合或语义变更，L3 必须对照新版 shlosilo.h 重编译）
 * - patch 不同 → -3（行为微调，L3 应重新 smoke；检查同样拒绝以保证 determinism）
 *
 * 注意：这与传统 semver「minor 增 = 向后兼容」**不同**——本项目 C ABI 处于
 * 0.x 阶段，minor 即破坏性位（与 0.x semver 约定一致）。进入 1.x 后应放宽为
 * major-only 检查。
 */
#define SHLOSILO_CABI_VERSION_MAJOR 0

#define SHLOSILO_CABI_VERSION_MINOR 3

#define SHLOSILO_CABI_VERSION_PATCH 0

/**
 * CLSAG 环签名（可变长度，取决于环大小）
 */
#define CLSAG_PROOF_MAX_LEN (32 * 16)

/**
 * ECDSA 签名（r, s 压缩序列化）
 *
 * 字节长度固定：32 (r) + 32 (s) = 64 bytes
 */
#define ECDSA_SIGNATURE_LEN 64

#define EDDSA_SIGNATURE_LEN 64

/**
 * FCMP++ 证明长度（待 Phase 7 实际确定）
 */
#define FCMP_PROOF_MAX_LEN 1024

/**
 * RSA-PSS 签名固定长度（512 bytes for RSA-4096）
 */
#define RSA_PSS_SIGNATURE_LEN 512

#define SCHNORR_SIGNATURE_LEN 64

/**
 * JSON 编码的 view key 字符串（Feather Wallet 兼容，最长 ~256 字符）
 */
#define JSON_MONERO_VIEWKEY_MAX_LEN 512

/**
 * 原始 payload 上限（codec 产出的 CBOR）
 */
#define UR_PAYLOAD_MAX_LEN 2048

/**
 * 完整 URI 上限：prefix + bytewords(payload+crc32) ≈ 2×payload + 头
 */
#define UR_URI_MAX_LEN 8192

/**
 * 多分片 payload 上限——对齐 TxTemplate 16 KiB（v2-安全 §4 体积护栏同源）
 */
#define MULTIPART_PAYLOAD_MAX_LEN 16384

/**
 * 单帧字符串上限：bytewords ≈ 2×data；data ≤ fragment(≤payload) → 2×16 KiB 裕量
 */
#define MULTIPART_FRAME_MAX_LEN 40960

/**
 * 单帧 payload 上限（单帧大 QR 通道走 ur_encode::encode，此处仅分片）
 */
#define DEFAULT_FRAGMENT_LEN 200

/**
 * 有状态多分片解码器。逐帧 `receive_frame()`，`progress()` 驱动 UI，
 * `complete()` 后 `payload()` 取结果（只读借用——caller 需要所有权时 clone/copy 走 budget）。
 * 审计 #5 P1-01: 会话累计保留内存预算——decoded/buffer/queue 中 Part.data
 * 总字节超过此值 = 异常会话,reset 清空(攻击者不能长期占用内存)。
 * payload 本身 ≤ 16KiB;2 倍裕量覆盖 fountain 消元中间态。
 */
#define MULTIPART_SESSION_RETAINED_MAX (MULTIPART_PAYLOAD_MAX_LEN * 2)

typedef struct UrMultipartDecoder UrMultipartDecoder;

/**
 * 有状态多分片编码器。`next_frame()` 产出 URI 帧字符串；
 * XMR 补扫场景用 `next_cyclic_frame()`。
 */
typedef struct UrMultipartEncoder UrMultipartEncoder;

/**
 * L3 提供：FreeRTOS pvPortMalloc 包装
 */
extern uint8_t *shlosilo_embedded_malloc(uintptr_t size);

/**
 * L3 提供：vPortFree 包装
 */
extern void shlosilo_embedded_free(uint8_t *ptr);

/**
 * L3 提供：panic 信息显示（LCD）+ 保持系统运行/刷新
 */
extern void shlosilo_panic_hook(const uint8_t *msg, uintptr_t len);

/**
 * shlosilo_sign_ffi — mnemonic + UR payload → 签名
 *
 * 返回 0 = Ok（长度写 *actual_len），负数 = 错误码。
 */
int shlosilo_sign_ffi(const uint16_t *mnemonic_indices,
                      int mnemonic_count,
                      const uint8_t *passphrase,
                      unsigned int passphrase_len,
                      const uint8_t *ur_payload,
                      unsigned int ur_payload_len,
                      unsigned int network,
                      uint8_t *output_buf,
                      unsigned int output_buf_len,
                      unsigned int *actual_len);

/**
 * shlosilo_sign_ur_ffi — 完整 UR 字符串 + mnemonic → 签名（P6.1d）
 *
 * L3 直接喂 `ur:crypto-psbt/...` / `ur:eth-sign-request/...` / `ur:xmr-txunsigned/...`，
 * UR 解码 + type tag 校验都在库内做（L3 薄、L1 厚）。
 *
 * **§B.5 RNG 注入扩展（2026-08-28）**：新增 entropy_ptr / entropy_len 参数——
 * XMR 签名 REQUIRED（≥16B，L3 承诺来源与 min-entropy）；BTC/ETH deterministic
 * backend 传 NULL/0 即可。同一 (keys, tx, entropy) → 同一签名（deterministic retry）。
 *
 * 返回 0 = Ok，负数 = 错误码；签名 bytes 写 output_buf。
 */
int shlosilo_sign_ur_ffi(const char *uri,
                         const uint16_t *mnemonic_indices,
                         int mnemonic_count,
                         const uint8_t *passphrase,
                         unsigned int passphrase_len,
                         unsigned int network,
                         const uint8_t *entropy_ptr,
                         unsigned int entropy_len,
                         uint8_t *output_buf,
                         unsigned int output_buf_len,
                         unsigned int *actual_len);

/**
 * shlosilo_export_readonly_ffi — mnemonic + path → 只读凭证 UR
 *
 * **P1-04（2026-08-29）**：seed 不再跨 FFI。入口收 mnemonic indices + passphrase，
 * 库内现场恢复 BIP-39 seed（栈 buffer，`SecretBytes::take` 接管清零），导出完成即弃。
 *
 * paths 为 flat u32 数组（hardened bit = 0x8000_0000），
 * `path_elem_count` 是这一个 path 的元素数（v1 单 path）。
 */
int shlosilo_export_readonly_ffi(const uint16_t *mnemonic_indices,
                                 int mnemonic_count,
                                 const uint8_t *passphrase,
                                 unsigned int passphrase_len,
                                 unsigned int network,
                                 const uint32_t *path_elems,
                                 unsigned int path_elem_count,
                                 unsigned int protocol,
                                 uint8_t *output_buf,
                                 unsigned int output_buf_len,
                                 unsigned int *actual_len);

/**
 * shlosilo_create_account_ffi — dice entropy → mnemonic(u16 LE 索引对)
 *
 * **P1-04（2026-08-29）**：`seed_out` 删除——seed 不跨 FFI（v2 安全模型）。
 * dice → mnemonic 是唯一产出；后续签名/导出直接收 mnemonic（库内现场恢复 seed）。
 * passphrase 保留（未来离线 create 时写进设备存储的元数据），当前仅做上限校验。
 */
int shlosilo_create_account_ffi(unsigned int word_count,
                                unsigned int sides,
                                const uint8_t *rolls,
                                unsigned int rolls_count,
                                const uint8_t *passphrase,
                                unsigned int passphrase_len,
                                uint8_t *mnemonic_buf,
                                unsigned int mnemonic_buf_len);

/**
 * 支持的 Network u8 列表（L3 启动时 UI dispatch 用）
 */
int shlosilo_supported_networks_ffi(uint8_t *output_buf,
                                    unsigned int output_buf_len,
                                    unsigned int *actual_len);

/**
 * 支持的 ExportProtocol u8 列表
 */
int shlosilo_supported_protocols_ffi(uint8_t *output_buf,
                                     unsigned int output_buf_len,
                                     unsigned int *actual_len);

/**
 * R3: 创建多分片编码器。成功返回句柄（非 null），失败返回 null。
 * type_name: ASCII 字母数字 + '-'（如 "xmr-txunsigned"）
 * L3 完成后必须调用 shlosilo_ur_encode_free。
 */
struct UrMultipartEncoder *shlosilo_ur_encode_begin(const char *type_name,
                                                    const uint8_t *payload,
                                                    unsigned int payload_len,
                                                    unsigned int max_fragment_len);

/**
 * R3: 取下一帧 URI 字符串（写 frame_buf，NUL 结尾）。
 * 返回 0 = Ok；负数 = 错误码。重复调用产出 fountain 冗余帧流。
 */
int shlosilo_ur_encode_next(struct UrMultipartEncoder *handle,
                            uint8_t *frame_buf,
                            unsigned int frame_buf_len,
                            unsigned int *actual_len);

/**
 * R3: XMR cyclic 补扫帧（seq 到顶回 1，无限循环供软件钱包补扫）
 */
int shlosilo_ur_encode_next_cyclic(struct UrMultipartEncoder *handle,
                                   uint8_t *frame_buf,
                                   unsigned int frame_buf_len,
                                   unsigned int *actual_len);

/**
 * R3: 释放编码器句柄。null 安全（幂等）。
 */
void shlosilo_ur_encode_free(struct UrMultipartEncoder *handle);

/**
 * R3: 创建多分片解码器。成功返回句柄，失败返回 null。
 */
struct UrMultipartDecoder *shlosilo_ur_decode_new(void);

/**
 * R3: 喂一帧 URI（NUL 结尾 C string）。
 * 返回 0 = Ok（accepted 状态写 *accepted_out：1=有新信息，0=重复帧）
 */
int shlosilo_ur_decode_feed(struct UrMultipartDecoder *handle,
                            const char *frame,
                            unsigned int *accepted_out);

/**
 * R3: 解码进度 0..=99（100 用 complete 表达）
 */
int shlosilo_ur_decode_progress(struct UrMultipartDecoder *handle);

/**
 * R3: 是否完成
 */
int shlosilo_ur_decode_complete(struct UrMultipartDecoder *handle);

/**
 * R3: 取完整 payload（写 payload_buf；实际长度写 actual_len）。
 * 完成前调用 → ERR_UNKNOWN；payload 超过 buf → ERR_BUFFER_TOO_SMALL（actual_len 写需求值）。
 */
int shlosilo_ur_decode_payload(struct UrMultipartDecoder *handle,
                               uint8_t *payload_buf,
                               unsigned int payload_buf_len,
                               unsigned int *actual_len);

/**
 * R3/P0-C（2026-09-01）：取解码后的 UR type（写 type_buf 为 NUL 结尾 ASCII）。
 * 完成前或无帧 → EncodingInvalidFormat；缓冲不足 → BufferTooSmall（actual_len 写需求值，含 NUL）。
 */
int shlosilo_ur_decode_type(struct UrMultipartDecoder *handle,
                            uint8_t *type_buf,
                            unsigned int type_buf_len,
                            unsigned int *actual_len);

/**
 * R3/P0-C（2026-09-01）：typed sign——multipart 重组后的 (type, payload) 垂直贯通签名。
 * type_name 必须是已知可签名的 UrTypeTag（拒绝 Unknown/任意字符串）；
 * payload 预算 = MULTIPART_PAYLOAD_MAX_LEN（16 KiB，对齐 multipart 重组上限）。
 */
int shlosilo_sign_typed_ffi(const char *type_name,
                            const uint8_t *payload,
                            unsigned int payload_len,
                            const uint16_t *mnemonic_indices,
                            int mnemonic_count,
                            const uint8_t *passphrase,
                            unsigned int passphrase_len,
                            unsigned int network,
                            const uint8_t *entropy_ptr,
                            unsigned int entropy_len,
                            uint8_t *output_buf,
                            unsigned int output_buf_len,
                            unsigned int *actual_len);

/**
 * R3: 释放解码器句柄。null 安全（幂等）。
 */
void shlosilo_ur_decode_free(struct UrMultipartDecoder *handle);

/**
 * extern "C" 返回版本字符串（C 端 strdup 后用）
 */
const uint8_t *shlosilo_version(void);

/**
 * extern "C" 返回 C ABI 版本字符串
 */
const uint8_t *shlosilo_cabi_version(void);

/**
 * L3 启动时校验 ABI 兼容性（major 必须匹配）
 *
 * 返回 0 = ABI 兼容，非 0 = 不兼容
 */
int32_t shlosilo_cabi_check(uint16_t l3_expected_major,
                            uint16_t l3_expected_minor,
                            uint16_t l3_expected_patch);
