/* shlosilo C-ABI — generated by cbindgen, do not edit by hand */

/*
 * The C host must provide these three hooks; the shlosilo staticlib links
 * against them (they live in flux/forgebox/staticlib, the C-host runtime
 * bundle, not in the forms core):
 *
 *   void  *shlosilo_embedded_malloc(size_t size);       // allocator backend
 *   void   shlosilo_embedded_free(void *ptr);
 *   void   shlosilo_panic_hook(const uint8_t *msg, size_t len);  // never returns
 *
 * The ForgeBox firmware implements them in shlosilo/embedded_alloc_glue.c
 * and src/tasks/shlosilo_smoke_task.c.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * APT address length ("0x" + 64 hex = 66 chars)
 */
#define APTOS_ADDRESS_LEN 66

#define SUI_ADDRESS_LEN 66

/**
 * Arweave address length (base64url-encoded 512-bit SHA-256 digest = 43 characters)
 */
#define ARWEAVE_ADDRESS_MAX_LEN 64

/**
 * BTC address (max 90 chars bech32 encoding)
 */
#define BTC_ADDRESS_MAX_LEN 90

/**
 * P2WPKH witness program length (20 bytes)
 */
#define P2WPKH_WITNESS_PROGRAM_LEN 20

/**
 * P2TR witness program length (32-byte x-only pubkey)
 */
#define P2TR_WITNESS_PROGRAM_LEN 32

/**
 * Cardano address length (bech32, up to ~100 chars)
 */
#define CARDANO_ADDRESS_MAX_LEN 120

/**
 * ETH address string length ("0x" + 40 hex = 42 chars)
 */
#define ETH_ADDRESS_LEN 42

/**
 * SOL address length (base58-encoded 32-byte pubkey, roughly 32-44 characters)
 */
#define SOL_ADDRESS_MAX_LEN 64

/**
 * Maximum XMR address length (base58-encoding 69 bytes = 8-byte × 8 + 5-byte tail → 11×8 + 7 = 95 chars, safe margin below 128)
 */
#define XMR_ADDRESS_MAX_LEN 128

/**
 * XRP address (classic base58 encoding, up to ~35 chars)
 */
#define XRP_ADDRESS_MAX_LEN 64

#define UNSIGNED_TX 0

/**
 * BIP-125: nSequence < 0xfffffffe means replaceable
 */
#define RBF_THRESHOLD 4294967294

/**
 * nLockTime height/time boundary (BIP-65 / Bitcoin Core)
 */
#define LOCKTIME_THRESHOLD 500000000

/**
 * BIP-68 disable flag
 */
#define SEQUENCE_LOCKTIME_DISABLE_FLAG (1 << 31)

/**
 * BIP-68 type flag (set = time, clear = height)
 */
#define SEQUENCE_LOCKTIME_TYPE_FLAG (1 << 22)

/**
 * Above this value counts as "huge" (21M BTC, in sats)
 */
#define MAX_MONEY_SATS (21000000 * 100000000)

/**
 * P2PKH dust
 */
#define DUST_SATS 546

/**
 * Witness program version (always 1 for P2TR per BIP-86)
 */
#define P2TR_WITNESS_VERSION 1

/**
 * CLSAG ring maximum length (XMR protocol default 11 = 1 real + 10 decoys)
 */
#define DEFAULT_RING_LEN 11

/**
 * CLSAG signature serialized length (64 bytes)
 * The actual monero-clsag Clsag struct serializes to ≈ 64 bytes
 */
#define CLSAG_PROOF_LEN 64

/**
 * Key image length (32 bytes compressed)
 */
#define KEY_IMAGE_LEN 32

/**
 * The wire of key-image-with-signature: a continuous stream of `[32B image][64B signature]` records,
 * aligned with keystone `KeyImages::to_bytes` / `From<&Vec<u8>>` (96B stride).
 */
#define KEY_IMAGE_RECORD_LEN 96

/**
 * Type 0: full borromean (pre-fork, deprecated)
 */
#define FULL 0

/**
 * Type 1: simple borromean (deprecated)
 */
#define SIMPLE 1

/**
 * Type 2: bulletproofs (per-output BP+ range proof)
 */
#define BULLETPROOFS 2

/**
 * Type 3: bulletproofs2 (aggregated BP+, post-fork 1788000)
 */
#define BULLETPROOFS_PLUS 3

/**
 * Entropy length lower bound (a misuse guard, not an entropy-quality check — see the module docs).
 */
#define ENTROPY_MIN_LEN 16

/**
 * XMR tx version: 2 = RingCT (post-fork, only valid in mainnet)
 */
#define TX_VERSION 2

/**
 * Legacy (pre-RingCT, deprecated)
 */
#define TX_OUT_GEN 0

/**
 * TxOutToKey: standard stealth output (RingCT compatible)
 */
#define TX_OUT_TO_KEY 2

/**
 * TxOutToTaggedKey: tagged-key output (subaddress)
 */
#define TX_OUT_TO_TAGGED_KEY 3

/**
 * Construct and sign a full transaction from TxConstructionData (P1-06 core entry point)
 *
 * **Input**:
 * - tx_data: parsed unsigned tx construction data (one tx)
 * - spend_sec / view_sec: derived wallet keys
 * - rng: randomness source (L3 injected; on device = TRNG)
 *
 * **Output**: fully signed Transaction (wire format ready to use)
 * Z3.2b: per-tx wire slot cap (matches business `TX_BYTES_SLOT_MAX`; the
 * real monerod wire is ~2KiB single-input, cap 16KiB covers multi-input).
 */
#define TX_WIRE_SLOT_MAX (16 * 1024)

/**
 * RSA-4096 maximum signature length (512 bytes for a 4096-bit key + PSS overhead)
 */
#define RSA_SIGNATURE_MAX_LEN 512

/**
 * secp256k1 uncompressed public key length (65 bytes, 0x04 || X(32) || Y(32))
 */
#define UNCOMPRESSED_POINT_LEN 65

/**
 * BIP-32 extended private key (78 bytes: version + depth + fp + chain_code + key + ...)
 */
#define EXTENDED_PRIVKEY_LEN 78

/**
 * BIP-67 sorted public key list (for the P2SH multisig redeem script)
 */
#define MAX_MULTISIG_SIGNERS 15

#define MAX_DEPTH 16

/**
 * BIP-32 hardened bit (highest bit)
 */
#define HARDENED_BIT 2147483648

/**
 * Soft index upper bound (unsigned 31-bit)
 */
#define MAX_SOFT_INDEX 2147483647

/**
 * SLIP-0010 extended private key (ed25519 uses a different bit field, 32 bytes long)
 */
#define SLIP10_EXTENDED_KEY_LEN 32

/**
 * Stage ids (u8): 1=ur_decode 2=pbkdf2_seed 3=bip32_derive 4=rlp_parse
 * 5=keccak_sighash 6=ecdsa_sign 7=y_parity 8=serialize.
 *
 * Defined once at module level (not per feature branch): callers use these in
 * every configuration, and a single definition keeps cbindgen's C header free
 * of duplicates.
 */
#define STAGE_UR_DECODE 1

#define STAGE_PBKDF2 2

#define STAGE_BIP32 3

#define STAGE_RLP 4

#define STAGE_KECCAK 5

#define STAGE_ECDSA 6

#define STAGE_Y_PARITY 7

#define STAGE_SERIALIZE 8

#define STAGE_COUNT 8

/**
 * base58check string maximum length
 */
#define BASE58_MAX_LEN 128

/**
 * base64 string maximum length
 */
#define BASE64_MAX_LEN 256

/**
 * bech32 maximum string length
 */
#define BECH32_MAX_LEN 128

/**
 * Keccak-256 output length
 */
#define KECCAK256_OUTPUT_LEN 32

/**
 * RIPEMD-160 output length
 */
#define RIPEMD160_OUTPUT_LEN 20

/**
 * SHA-256 output length
 */
#define SHA256_OUTPUT_LEN 32

/**
 * SHA-512 output length
 */
#define SHA512_OUTPUT_LEN 64

/**
 * BIP-39 seed length (64 bytes)
 */
#define BIP39_SEED_LEN 64

#define MAX_MNEMONIC_WORDS 24









/**
 * Z5.2b: generator table storage slot already provided/consumed (terminal).
 * A bare code in the -10..-40 FFI space (same style as -21/-30), not an enum
 * variant: this is an FFI-contract outcome, not a `ShlosiloError` kind.
 */
#define ERR_SLOT_CONSUMED -22



/**
 * Full shlosilo version (cabi + runtime)
 */
#define SHLOSILO_VERSION_MAJOR 0

#define SHLOSILO_VERSION_MINOR 5

#define SHLOSILO_VERSION_PATCH 0

/**
 * C ABI version (**independent of the runtime version** — L3 must validate the ABI version matches)
 *
 * ABI version incompatibility rules (`shlosilo_cabi_check` implements **strict equality**):
 * - major differs → -1 (ABI incompatible; signature/error-code layout changed)
 * - minor differs → -2 (exported function set or semantics changed; L3 must recompile against the new shlosilo.h)
 * - patch differs → -3 (minor behavior tweaks; L3 should re-smoke; the check rejects it too, for determinism)
 *
 * Note: unlike traditional semver where "minor bump = backward compatible", this project's C ABI is in
 * its 0.x stage, where minor is the breaking component (consistent with 0.x semver convention). After entering 1.x it should relax to
 * a major-only check.
 */
#define SHLOSILO_CABI_VERSION_MAJOR 0

#define SHLOSILO_CABI_VERSION_MINOR 3

#define SHLOSILO_CABI_VERSION_PATCH 0

/**
 * CLSAG ring signature (variable length, depends on ring size)
 */
#define CLSAG_PROOF_MAX_LEN (32 * 16)

/**
 * ECDSA signature (r, s compact serialization)
 *
 * Fixed byte length: 32 (r) + 32 (s) = 64 bytes
 */
#define ECDSA_SIGNATURE_LEN 64

#define EDDSA_SIGNATURE_LEN 64

/**
 * FCMP++ proof length (to be determined in Phase 7)
 */
#define FCMP_PROOF_MAX_LEN 1024

/**
 * RSA-PSS signature fixed length (512 bytes for RSA-4096)
 */
#define RSA_PSS_SIGNATURE_LEN 512

#define SCHNORR_SIGNATURE_LEN 64

#define TX_PHASES 11

/**
 * Protocol-hard: Monero fixed ring size (post-v13 CLSAG). Never tunable.
 * Z5.3 pool cut: BP+ prove multiexp scratch, in (Scalar, EdwardsPoint)
 * entries. Bound = `2 * padded_pow_of_2(MAX_COMMITMENTS * 64) + 2` = 2*1024+2
 * (the A-terms worst case; WIP L/R need less). Over-cap in the prove chain
 * is an explicit error before any proving starts.
 */
#define SIGN_WS_BP_TERMS 2050

/**
 * Z5.3 D-cut: the Straus scratch byte pool (mirrors the vendor's
 * `StrausScratch::storage_bytes(SIGN_WS_BP_TERMS)`; a pin test asserts the
 * two agree — same source-of-truth discipline as the Z3.3b ws layout).
 */
#define SIGN_WS_BP_STRAUS_BYTES ((SIGN_WS_BP_TERMS * 2816) + 64)

/**
 * Z5.2b: decompressed generator point element size (curve25519-dalek
 * `EdwardsPoint` repr: 4 x [u64; 5]). Pinned by a static assert in c_abi;
 * the C side sizes table buffers as points * this constant.
 */
#define SHLOSILO_GENPOINT_SIZE 160

/**
 * Z5.2b: per-set generator table storage (deploy constants; pinned ==
 * `generator_table_sizes` runtime query by tests/ffi_gencache_provide.rs —
 * same source-of-truth contract as the Z3.3b ws layout).
 */
#define SHLOSILO_GENCACHE_G_BYTES 163840

#define SHLOSILO_GENCACHE_H_BYTES 163840

#define SHLOSILO_GENCACHE_BLOB_BYTES 262144

#define RING_MAX 16

/**
 * Soft: additional tx keys per source/output (real traffic 1-2).
 */
#define EXTRA_KEYS_MAX 8

/**
 * Soft: `tx_extra` nonce payload bytes (payment IDs are 8/9B).
 */
#define TX_EXTRA_NONCE_MAX 32

/**
 * Soft: `tx_extra` additional pubkeys (subaddress sends; one per output).
 */
#define TX_EXTRA_PUBKEYS_MAX 16

/**
 * Soft: `original` address-string bytes (Monero base58 addresses: standard 95,
 * integrated 106 chars — real traffic never exceeds 106). Over-cap is an
 * explicit EncodingInvalidFormat Err (Z3.1 leaf: the container Vec is gone).
 */
#define DEST_ORIGINAL_MAX 106

/**
 * Workspace: plaintext scratch == max unsigned-txset plain budget.
 */
#define SIGN_WS_PLAIN 16384

/**
 * Workspace: unsigned-model tx slots.
 */
#define SIGN_WS_TXES 8

/**
 * Workspace: source entries (flat, all txes).
 */
#define SIGN_WS_SOURCES 32

/**
 * Workspace: splitted destinations (flat).
 */
#define SIGN_WS_SPLITS 64

/**
 * Workspace: selected-transfers bytes (flat).
 */
#define SIGN_WS_SEL 256

/**
 * Workspace: tx_extra bytes == max plain budget.
 */
#define SIGN_WS_EXTRA 16384

/**
 * Workspace: model destinations (flat).
 */
#define SIGN_WS_DESTS 64

/**
 * Workspace: subaddress indices (flat).
 */
#define SIGN_WS_SUBIDX 256

/**
 * Workspace: PendingTx slots.
 */
#define SIGN_WS_PTX 8

/**
 * Workspace: signed-tx wire bytes (TX_WIRE_SLOT_MAX per tx).
 */
#define SIGN_WS_TX_BYTES ((16 * 1024) * 8)

/**
 * Workspace: key images (flat).
 */
#define SIGN_WS_KI 32

/**
 * Workspace: tx key image records (flat).
 */
#define SIGN_WS_TKI 128

/**
 * Workspace: selected-transfers record bytes (flat).
 */
#define SIGN_WS_SEL_OUT 256

/**
 * Workspace: key-image string bytes (67 per source).
 */
#define SIGN_WS_KSTR (67 * 32)

/**
 * Workspace: UR decode — decoded-parts slots (FountainWs pool).
 */
#define UR_WS_DECODED_SLOTS 256

/**
 * Workspace: UR decode — work-buffer slots.
 */
#define UR_WS_BUFFER_SLOTS 256

/**
 * Workspace: UR decode — cascade queue slots.
 */
#define UR_WS_QUEUE_SLOTS 256

/**
 * Workspace: UR decode — received-sequence slots (the full fountain sequence
 * space: MAX_TOTAL_FRAMES).
 */
#define UR_WS_RECEIVED_SLOTS 4096

/**
 * Workspace: records-face destinations (flat).
 */
#define SIGN_WS_RECORD_DESTS 64

/**
 * ClsagProof serialized cap: pseudo_out (32) + s[RING_MAX] (32*16) + c1 (32) + D (32).
 * Layout per clsag.rs sign(): `pseudo_out(32) ‖ s[mixin+1] ‖ c1 ‖ D`.
 */
#define CLSAG_PROOF_MAX (32 * (RING_MAX + 3))

/**
 * JSON-encoded view key string (Feather Wallet compatible, max ~256 characters)
 */
#define JSON_MONERO_VIEWKEY_MAX_LEN 512

/**
 * Raw payload upper bound (CBOR produced by codecs)
 */
#define UR_PAYLOAD_MAX_LEN 2048

/**
 * Full URI upper bound: prefix + bytewords(payload+crc32) ≈ 2×payload + header
 */
#define UR_URI_MAX_LEN 8192

/**
 * Multipart payload limit — aligned with TxTemplate 16 KiB (same source as the v2-security §4 size guardrail)
 */
#define MULTIPART_PAYLOAD_MAX_LEN 16384

/**
 * Single-frame string limit: bytewords ≈ 2×data; data ≤ fragment (≤ payload) → 2×16 KiB margin
 */
#define MULTIPART_FRAME_MAX_LEN 40960

/**
 * Single-frame payload limit (the single-frame large-QR channel goes through ur_encode::encode; only fragmentation here)
 */
#define DEFAULT_FRAGMENT_LEN 200

/**
 * Stateful multipart decoder. Feed frames one by one with `receive_frame()`, drive the UI with `progress()`,
 * after `complete()` take the result via `payload()` (read-only borrow — clone/copy within budget when the caller needs ownership).
 * Audit #5 P1-01: cumulative retained memory budget for the session — when the total bytes of Part.data across
 * decoded/buffer/queue exceed this value = abnormal session, reset to clear (an attacker cannot hold memory long-term).
 * The payload itself is <= 16 KiB; a 2× margin covers fountain elimination intermediate states.
 */
#define MULTIPART_SESSION_RETAINED_MAX (MULTIPART_PAYLOAD_MAX_LEN * 2)

typedef struct UrMultipartDecoder UrMultipartDecoder;

/**
 * Stateful multipart encoder. `next_frame_into()` produces URI frame text into a
 * caller buffer; XMR re-scan scenarios use `next_cyclic_frame_into()`.
 */
typedef struct UrMultipartEncoder UrMultipartEncoder;

/**
 * C-ABI: register the millisecond clock callback (no-op when the feature is off).
 *
 * # Safety
 * `fptr` must be a valid `extern "C" fn() -> u32` on the target.
 */
void shlosilo_timing_set_clock_fn(uint32_t fptr);

/**
 * C-ABI: read one stage's measured milliseconds (0 when the feature is off).
 */
uint32_t shlosilo_timing_get_stage(uint8_t stage);

/**
 * C-ABI: total measured sign ms (0 when the feature is off).
 */
uint32_t shlosilo_timing_get_total(void);

/**
 * C-ABI: reset all counters (no-op when the feature is off).
 */
void shlosilo_timing_reset(void);

/**
 * shlosilo_sign_ffi — mnemonic + UR payload → signature
 *
 * Returns 0 = Ok (length written to *actual_len), negative = error code.
 */
int shlosilo_sign_ffi(const uint16_t *mnemonic_indices,
                      int mnemonic_count,
                      const uint8_t *passphrase,
                      unsigned int passphrase_len,
                      const uint8_t *ur_payload,
                      unsigned int ur_payload_len,
                      unsigned int network,
                      uint8_t *output_buf,
                      unsigned int output_buf_len,
                      unsigned int *actual_len,
                      uint8_t *ws,
                      unsigned int ws_len);

/**
 * Z3.3b: sign workspace capacity query (C-ABI workspace contract v1 — the
 * capacity stays a RUNTIME query, never frozen into the ABI).
 *
 * Pure: no RNG consumption, no secret derivation, no output side effects.
 * The value comes from `SignWsLayout::compute()` — the SAME computation the
 * workspace carve uses (contract 3: one layout source of truth).
 */
unsigned int shlosilo_sign_ws_len(void);

/**
 * Z3.3c: encode-handle workspace capacity query (C-ABI workspace contract v1 —
 * runtime query, never frozen into the ABI). Pure: no state, no side effects.
 */
unsigned int shlosilo_ur_encode_ws_len(void);

/**
 * Z3.3c: decode-handle workspace capacity query (pools + handle, alignment
 * slop included). Pure: no state, no side effects. Same layout source as the
 * placement carve (contract 3).
 */
unsigned int shlosilo_ur_decode_ws_len(void);

/**
 * shlosilo_sign_ur_ffi — full UR string + mnemonic → signature (P6.1d)
 *
 * L3 feeds `ur:crypto-psbt/...` / `ur:eth-sign-request/...` / `ur:xmr-txunsigned/...` directly;
 * UR decoding + type tag validation both happen inside the library (thin L3, thick L1).
 *
 * **§B.5 RNG injection extension (2026-08-28)**: new entropy_ptr / entropy_len parameters —
 * REQUIRED for XMR signing (≥16B; L3 commits to the source and min-entropy); for BTC/ETH deterministic
 * backends, pass NULL/0. Same (keys, tx, entropy) → same signature (deterministic retry).
 *
 * Returns 0 = Ok, negative = error code; signature bytes are written to output_buf.
 */
int shlosilo_sign_ur_ffi(const char *uri,
                         const uint16_t *mnemonic_indices,
                         int mnemonic_count,
                         const uint8_t *passphrase,
                         unsigned int passphrase_len,
                         unsigned int network,
                         const uint8_t *entropy_ptr,
                         unsigned int entropy_len,
                         uint8_t *output_buf,
                         unsigned int output_buf_len,
                         unsigned int *actual_len,
                         uint8_t *ws,
                         unsigned int ws_len);

/**
 * shlosilo_export_readonly_ffi — mnemonic + path → read-only credential UR
 *
 * **P1-04 (2026-08-29)**: seed no longer crosses the FFI. The entry takes mnemonic indices + passphrase,
 * restores the BIP-39 seed on the spot inside the library (stack buffer, `SecretBytes::take` takes over zeroing), discarded once export completes.
 *
 * paths is a flat u32 array (hardened bit = 0x8000_0000),
 * `path_elem_count` is the element count of this one path (v1: single path).
 */
int shlosilo_export_readonly_ffi(const uint16_t *mnemonic_indices,
                                 int mnemonic_count,
                                 const uint8_t *passphrase,
                                 unsigned int passphrase_len,
                                 unsigned int network,
                                 const uint32_t *path_elems,
                                 unsigned int path_elem_count,
                                 unsigned int protocol,
                                 uint8_t *output_buf,
                                 unsigned int output_buf_len,
                                 unsigned int *actual_len);

/**
 * shlosilo_create_account_ffi — dice entropy → mnemonic (u16 LE index pairs)
 *
 * **P1-04 (2026-08-29)**: `seed_out` removed — seed does not cross the FFI (v2 security model).
 * dice → mnemonic is the sole output; later signing/export takes mnemonic directly (seed restored on the spot inside the library).
 * passphrase kept (metadata to be written into device storage on a future offline create); currently only length-cap validated.
 */
int shlosilo_create_account_ffi(unsigned int word_count,
                                unsigned int sides,
                                const uint8_t *rolls,
                                unsigned int rolls_count,
                                const uint8_t *passphrase,
                                unsigned int passphrase_len,
                                uint8_t *mnemonic_buf,
                                unsigned int mnemonic_buf_len);

/**
 * List of supported Network u8 values (for UI dispatch at L3 startup)
 */
int shlosilo_supported_networks_ffi(uint8_t *output_buf,
                                    unsigned int output_buf_len,
                                    unsigned int *actual_len);

/**
 * List of supported ExportProtocol u8 values
 */
int shlosilo_supported_protocols_ffi(uint8_t *output_buf,
                                     unsigned int output_buf_len,
                                     unsigned int *actual_len);

/**
 * INV-1: pure probe — reports the required buffer sizes for a generator set.
 * No side effects: does not touch the registry slot, consumes no RNG, derives
 * no secrets. Values == what `shlosilo_gencache_provide_table` requires.
 *
 * # Safety
 * All three out-pointers must be valid for writes of `u32` and non-aliased.
 */
int32_t shlosilo_gencache_table_sizes(int32_t set,
                                      uint32_t *g_bytes,
                                      uint32_t *h_bytes,
                                      uint32_t *blob_bytes);

/**
 * INV-2/3/4: provide the decompressed-table storage for one generator set.
 * All validation happens before any state change or write; success commits
 * the slot atomically (CONSUMED); failure leaves state unchanged (retry OK).
 *
 * # Safety
 * `g`/`h` must be 8-aligned and point to at least `*g_bytes`/`*h_bytes`
 * writable bytes; `blob` to at least `*blob_bytes`. The used regions must be
 * pairwise disjoint (enforced). The buffers must outlive every generator
 * use — they are written ONCE at first generator use and read thereafter.
 * Size out-pointers must be valid for read/write and non-aliased.
 */
int32_t shlosilo_gencache_provide_table(int32_t set,
                                        uint8_t *g,
                                        uint32_t *g_bytes,
                                        uint8_t *h,
                                        uint32_t *h_bytes,
                                        uint8_t *blob,
                                        uint32_t *blob_bytes);

/**
 * R3: create a multipart encoder. Returns a handle (non-null) on success, null on failure.
 * type_name: ASCII alphanumeric + '-' (e.g. "xmr-txunsigned")
 * L3 must call shlosilo_ur_encode_free when done.
 */
struct UrMultipartEncoder *shlosilo_ur_encode_begin(const char *type_name,
                                                    const uint8_t *payload,
                                                    unsigned int payload_len,
                                                    unsigned int max_fragment_len,
                                                    uint8_t *ws,
                                                    unsigned int ws_len);

/**
 * R3: get the next frame URI string (written to frame_buf, NUL-terminated).
 * Returns 0 = Ok; negative = error code. Repeated calls produce the fountain redundancy frame stream.
 *
 * frame_buf_len must be at least 1024 (FRAME_BUF_MAX_LEN); shorter buffers are
 * rejected with BufferTooSmall even though a 200-byte-fragment frame is ~460 chars.
 */
int shlosilo_ur_encode_next(struct UrMultipartEncoder *handle,
                            uint8_t *frame_buf,
                            unsigned int frame_buf_len,
                            unsigned int *actual_len);

/**
 * R3: XMR cyclic catch-up frames (seq wraps back to 1 at the top, looping forever so software wallets can catch up)
 *
 * frame_buf_len must be at least 1024 (FRAME_BUF_MAX_LEN); shorter buffers are
 * rejected with BufferTooSmall even though a 200-byte-fragment frame is ~460 chars.
 */
int shlosilo_ur_encode_next_cyclic(struct UrMultipartEncoder *handle,
                                   uint8_t *frame_buf,
                                   unsigned int frame_buf_len,
                                   unsigned int *actual_len);

/**
 * R3: release the encoder handle. Null-safe (idempotent).
 */
void shlosilo_ur_encode_free(struct UrMultipartEncoder *handle);

/**
 * R3: create a multipart decoder. Returns a handle on success, null on failure.
 */
struct UrMultipartDecoder *shlosilo_ur_decode_new(uint8_t *ws, unsigned int ws_len);

/**
 * R3: feed one frame URI (NUL-terminated C string).
 * Returns 0 = Ok (accepted status written to *accepted_out: 1 = new information, 0 = duplicate frame)
 */
int shlosilo_ur_decode_feed(struct UrMultipartDecoder *handle,
                            const char *frame,
                            unsigned int *accepted_out);

/**
 * R3: decode progress 0..=99 (100 is expressed via complete)
 */
int shlosilo_ur_decode_progress(struct UrMultipartDecoder *handle);

/**
 * R3: whether decoding is complete
 */
int shlosilo_ur_decode_complete(struct UrMultipartDecoder *handle);

/**
 * R3: get the complete payload (written to payload_buf; actual length written to actual_len).
 * Calling before completion → ERR_UNKNOWN; payload larger than buf → ERR_BUFFER_TOO_SMALL (actual_len gets the required value).
 */
int shlosilo_ur_decode_payload(struct UrMultipartDecoder *handle,
                               uint8_t *payload_buf,
                               unsigned int payload_buf_len,
                               unsigned int *actual_len);

/**
 * R3/P0-C (2026-09-01): get the decoded UR type (written to type_buf as NUL-terminated ASCII).
 * Before completion or with no frames → EncodingInvalidFormat; buffer too small → BufferTooSmall (actual_len gets the required value, including NUL).
 */
int shlosilo_ur_decode_type(struct UrMultipartDecoder *handle,
                            uint8_t *type_buf,
                            unsigned int type_buf_len,
                            unsigned int *actual_len);

/**
 * R3/P0-C (2026-09-01): typed sign — vertical pass-through signing of the (type, payload) reassembled from multipart.
 * type_name must be a known signable UrTypeTag (Unknown/arbitrary strings are rejected);
 * payload budget = MULTIPART_PAYLOAD_MAX_LEN (16 KiB, aligned with the multipart reassembly cap).
 */
int shlosilo_sign_typed_ffi(const char *type_name,
                            const uint8_t *payload,
                            unsigned int payload_len,
                            const uint16_t *mnemonic_indices,
                            int mnemonic_count,
                            const uint8_t *passphrase,
                            unsigned int passphrase_len,
                            unsigned int network,
                            const uint8_t *entropy_ptr,
                            unsigned int entropy_len,
                            uint8_t *output_buf,
                            unsigned int output_buf_len,
                            unsigned int *actual_len,
                            uint8_t *ws,
                            unsigned int ws_len);

/**
 * R3: release the decoder handle. Null-safe (idempotent).
 */
void shlosilo_ur_decode_free(struct UrMultipartDecoder *handle);

/**
 * C-ABI: register the millisecond clock for CN phase timing.
 *
 * # Safety
 * `clock_fptr` must be a valid `extern "C" fn() -> u32` address (ARM thumb ok).
 */
void shlosilo_cn_timing_set_clock(uint32_t clock_fptr);

/**
 * C-ABI: reset all CN phase counters.
 */
void shlosilo_cn_timing_reset(void);

/**
 * C-ABI: read one phase's accumulated ms (0 for unknown phase).
 */
uint32_t shlosilo_cn_timing_phase(uint8_t phase);

/**
 * C-ABI: register the flash-backend callbacks. Call once from C init (before the first
 * XMR sign). `load_fptr`/`store_fptr` are ARM thumb addresses of the C functions.
 *
 * # Safety
 * Both pointers must be valid `extern "C"` functions with the documented signatures.
 *
 * Single definition with a cfg-split body (feature on: real hooks; off: no-op)
 * so the C host always links and cbindgen emits exactly one declaration.
 */
void shlosilo_gen_cache_set_hooks(uint32_t load_fptr, uint32_t store_fptr);

uint64_t shlosilo_perf_fmul(uint32_t iters);

uint64_t shlosilo_perf_fsq(uint32_t iters);

uint64_t shlosilo_perf_select(uint32_t iters);

uint64_t shlosilo_perf_madd(uint32_t iters);

uint64_t shlosilo_perf_quadruple(uint32_t iters);

uint64_t shlosilo_perf_ct_chunk(uint32_t n, uint32_t iters);

uint64_t shlosilo_perf_vartime_2term(uint32_t iters);

uint64_t shlosilo_perf_select_affine(uint32_t iters);

uint64_t shlosilo_perf_madd_affine(uint32_t iters);

/**
 * Chunked CT multiexp with full-width scalars (in-situ shape): n terms,
 * chunk terms per Straus call, `iters` repetitions.
 */
uint64_t shlosilo_perf_ct_chunked(uint32_t n, uint32_t chunk, uint32_t iters);

/**
 * Vartime 2-term multiexp with full-width scalars (the fold shape).
 */
uint64_t shlosilo_perf_vartime_2term_fw(uint32_t iters);

/**
 * The BP+ WIP L/R call chain replicated in a bench (see
 * monero_bulletproofs::bench_multiexp_chain): tuple Vec -> chunked
 * multiexp wrapper -> optional INV_EIGHT + compress tail. `gen_points`
 * selects generator-table points (in-situ source) vs the basepoint.
 */
uint64_t shlosilo_perf_xchain(uint32_t n, uint32_t iters, uint32_t tail, uint32_t gen_points);

/**
 * C-ABI: register the millisecond clock for prove-phase timing. Call from C init
 * right after `shlosilo_timing_set_clock_fn` (same clock function address works).
 *
 * # Safety
 * `clock_fptr` must be a valid `extern "C" fn() -> u32` address (ARM thumb ok).
 */
void shlosilo_bp_timing_set_clock(uint32_t clock_fptr);

/**
 * C-ABI: reset all prove-phase counters.
 */
void shlosilo_bp_timing_reset(void);

/**
 * C-ABI: read one phase's accumulated ms (0 for unknown phase).
 */
uint32_t shlosilo_bp_timing_phase(uint8_t phase);

/**
 * C-ABI: register the millisecond clock for tx-phase timing.
 *
 * # Safety
 * `clock_fptr` must be a valid `extern "C" fn() -> u32` address (ARM thumb ok).
 */
void shlosilo_tx_phase_set_clock(uint32_t clock_fptr);

/**
 * C-ABI: reset all tx-phase counters.
 */
void shlosilo_tx_phase_reset(void);

/**
 * C-ABI: read one phase's accumulated ms (0 for unknown phase).
 */
uint32_t shlosilo_tx_phase_phase(uint8_t phase);

/**
 * extern "C" returning the version string (C side strdups it before use)
 */
const uint8_t *shlosilo_version(void);

/**
 * extern "C" returning the C ABI version string
 */
const uint8_t *shlosilo_cabi_version(void);

/**
 * Validate ABI compatibility at L3 startup (major must match)
 *
 * Returns 0 = ABI compatible, non-zero = incompatible
 */
int32_t shlosilo_cabi_check(uint16_t l3_expected_major,
                            uint16_t l3_expected_minor,
                            uint16_t l3_expected_patch);
