//! P6.3/P1-06 XMR unsigned_txset end-to-end: entropy → BIP39 seed → Monero derivation →
//! decrypt → epee deserialize → compare against the known P6.3 parse result
//!
//! fixture：
//! - tests/fixtures/unsigned_txset.bin (generated by Feather wallet-rpc, 2047B encrypted)
//! - tests/fixtures/txset_plain.bin (P6.3 python-decrypted plaintext, 1952B)
//! - /home/komo/testTX/unsigned_txset_meta.json（fee/dest/tx_key）

use shlosilo::chain::xmr::unsigned_txset::{decrypt_unsigned_txset, deserialize_unsigned_tx};

const ENCRYPTED: &[u8] = include_bytes!("fixtures/unsigned_txset.bin");
const PLAIN: &[u8] = include_bytes!("fixtures/txset_plain.bin");

/// P1-06: decrypt the unsigned_txset fixture
///
/// Note: the XMR fixture is an **independent wallet** (not the entropy f284... of test260824-sig);
/// its view key is an external credential obtained via the P6.3 wallet-rpc viewkey command.
/// The test injects it via the environment variable SHLOSILO_TEST_XMR_VIEW_SK ([REDACTED] principle, no hardcoding).
#[test]
#[ignore = "X7: needs external credentials/env (SHLOSILO_TEST_XMR_*) — missing env no longer silently counts as passed; run: cargo test -- --ignored with env injected"]
fn decrypt_with_external_view_key() {
    let view_hex = std::env::var("SHLOSILO_TEST_XMR_VIEW_SK");
    let Ok(view_hex) = view_hex else {
        eprintln!(
            "SKIP: SHLOSILO_TEST_XMR_VIEW_SK not set (XMR fixture view key is external credential)"
        );
        return;
    };
    let view_sk: [u8; 32] = {
        let v: Vec<u8> = (0..view_hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&view_hex[i..i + 2], 16).unwrap())
            .collect();
        v.try_into().expect("32-byte view key")
    };
    let plain = decrypt_unsigned_txset(ENCRYPTED, &view_sk).expect("decrypt with real view key");
    assert_eq!(*plain, PLAIN, "plaintext must match P6.3 python result");
    let utx = deserialize_unsigned_tx(&plain).expect("deserialize");
    assert!(!utx.txes.is_empty(), "at least one tx");
    let tx = &utx.txes[0];
    let src = &tx.sources[0];
    assert_eq!(src.outputs.len(), 16, "ring size 16 (P6.3)");
    assert_eq!(src.real_output, 13, "real output index 13 (P6.3)");
    assert_eq!(src.amount, 2_000_000_000, "input 0.002 XMR (P6.3)");
    let out_sum: u64 = tx.splitted_dsts.iter().map(|d| d.amount).sum();
    assert_eq!(out_sum + 30_640_000, src.amount, "fee = 30640000 (P6.3)");
    let dest = &tx.splitted_dsts[1];
    assert_eq!(dest.amount, 100_000_000, "DEST1 1 XMR (P6.3)");
    assert!(dest.is_subaddress, "DEST1 is subaddress (P6.3)");
    let change = &tx.change_dts;
    assert!(!change.is_subaddress, "change to main address (P6.3)");
}

/// P1-06: P6.3 already-decrypted plaintext → epee deserialize → structural comparison
#[test]
fn deserialize_p63_plain() {
    let utx = deserialize_unsigned_tx(PLAIN).expect("deserialize P6.3 plaintext");
    let tx = &utx.txes[0];
    assert_eq!(tx.sources.len(), 1);
    let src = &tx.sources[0];
    assert_eq!(src.outputs.len(), 16);
    assert_eq!(src.real_output, 13);
    assert_eq!(src.amount, 2_000_000_000);
    assert!(src.rct);
    assert_eq!(src.multisig_kLRki.k, [0u8; 32], "non-multisig kLRki zero");
    // outputs：splitted_dsts = [change(1869360000, main), dest(100000000, subaddress)]
    assert_eq!(tx.splitted_dsts.len(), 2, "change + dest (P6.3)");
    assert_eq!(
        tx.splitted_dsts[0].amount, 1_869_360_000,
        "splitted[0]=change"
    );
    assert!(!tx.splitted_dsts[0].is_subaddress);
    assert_eq!(tx.splitted_dsts[1].amount, 100_000_000);
    assert!(tx.splitted_dsts[1].is_subaddress);
    assert_eq!(
        tx.change_dts.amount, 1_869_360_000,
        "change 1869360000 (P6.3)"
    );
    assert_eq!(
        tx.change_dts.spend_public_key,
        tx.splitted_dsts[0].spend_public_key
    );
    // RCTConfig (real fixture value, consistent with keystone\'s line-by-line parse):
    // version=0, range_proof_type=3(Bulletproof), bp_version=4(RCTTypeBulletproof2)
    // — this was the value when Feather wallet-rpc generated it (not BP+; mainnet defaults evolve with version)
    assert_eq!(
        tx.rct_config.range_proof_type, 3,
        "RangeProofType::Bulletproof"
    );
    assert_eq!(tx.rct_config.bp_version, 4, "RCTTypeBulletproof2 (fixture)");
    assert_eq!(tx.subaddr_indices, vec![1], "subaddress index 1 (P6.3)");
    // fee check: input − change(change_dts) − dest(splitted[1]) = fee
    let fee = src.amount - tx.change_dts.amount - tx.splitted_dsts[1].amount;
    assert_eq!(fee, 30_640_000, "fee 30640000 (P6.3)");
}
