/* shlosilo_ui.c - product UI: direct-write 1bpp renderer + touch buttons.
 *
 * The forgebox product line (D1) owns the panel with this module - no LVGL.
 * LVGL stays as the bring-up diagnostics renderer behind the SMOKE_SCREEN
 * build switch (exactly one renderer owns the screen per build).
 *
 * Model: a 1bpp canvas (480x800 = 46.9 KiB, SRAM heap) holds the current
 * frame; ui_flush() expands it to RGB565 rows in a band buffer and streams
 * each band through LcdDraw() (8080-parallel DMA). Text uses the Terminus
 * 8x16 blob (ui_font.c), byte-identical to the pico2 host's font. Layout
 * constants live in ui_layout.h (shared with the host preview script).
 *
 * Touch: FT6336 polled via TouchGetStatus() (~40 ms), press-edge detection,
 * two text buttons (`back` left / `continue` right). Every press echoes on
 * the footer line:  last: <event> (x,y). The footer also carries the build
 * identity (git hash) and the touch probe state - the on-screen diagnostic
 * channel that replaces a console.
 */
#include "shlosilo_ui.h"
#include "ui_layout.h"
#include "ui_font.h"
#include "hal_lcd.h"
#include "hal_touch.h"
#include "user_memory.h"
#include "version.h"
#include "cmsis_os.h"
#include <stdio.h>
#include <string.h>

/* fw_identity.h is generated by CMake at configure time (build dir):
 *     #define FIRMWARE_GIT_HASH "<short-hash>[-dirty]"  */
#include "fw_identity.h"

#ifndef FIRMWARE_GIT_HASH
#define FIRMWARE_GIT_HASH "dev"
#endif

#define FB_STRIDE  (UI_FB_W / 8)
#define FB_BYTES   (FB_STRIDE * UI_FB_H)

/* Flush band height; UI_FB_H must be a multiple of this. */
#define UI_BAND_ROWS  40
#define UI_BAND_BYTES (UI_FB_W * UI_BAND_ROWS * 2)

typedef enum {
    PAGE_WELCOME = 0,
    PAGE_SCAN,
} UiPage;

static uint8_t *g_fb;
static uint8_t *g_band;
static UiPage g_page = PAGE_WELCOME;
static char g_last[48] = "last: -";

/* ---------------- canvas primitives (inclusive coordinates) ---------------- */

static void put_px(int x, int y)
{
    if ((unsigned)x < UI_FB_W && (unsigned)y < UI_FB_H) {
        g_fb[y * FB_STRIDE + (x >> 3)] |= (uint8_t)(0x80u >> (x & 7));
    }
}

static void fill_rect(int x, int y, int w, int h)
{
    for (int yy = y; yy < y + h; yy++) {
        for (int xx = x; xx < x + w; xx++) {
            put_px(xx, yy);
        }
    }
}

static void rect_outline(int x0, int y0, int x1, int y1, int t)
{
    for (int k = 0; k < t; k++) {
        fill_rect(x0 + k, y0 + k, x1 - x0 - 2 * k + 1, 1);
        fill_rect(x0 + k, y1 - k, x1 - x0 - 2 * k + 1, 1);
        fill_rect(x0 + k, y0 + k, 1, y1 - y0 - 2 * k + 1);
        fill_rect(x1 - k, y0 + k, 1, y1 - y0 - 2 * k + 1);
    }
}

static int text_w(const char *s, int scale)
{
    return (int)strlen(s) * UI_FONT_GLYPH_W * scale;
}

static void draw_text(int x, int y, const char *s, int scale)
{
    for (const char *p = s; *p != '\0'; p++) {
        int c = (unsigned char)*p;
        const uint8_t *g = ui_font_8x16[(c >= 0x20 && c <= 0x7E) ? (c - 0x20)
                                                                : ('?' - 0x20)];
        for (int row = 0; row < UI_FONT_GLYPH_H; row++) {
            uint8_t bits = g[row];
            if (bits == 0) {
                continue;
            }
            for (int col = 0; col < UI_FONT_GLYPH_W; col++) {
                if (bits & (0x80u >> col)) {
                    fill_rect(x + col * scale, y + row * scale, scale, scale);
                }
            }
        }
        x += UI_FONT_GLYPH_W * scale;
    }
}

static void draw_text_center(int y, const char *s, int scale)
{
    draw_text((UI_FB_W - text_w(s, scale)) / 2, y, s, scale);
}

/* ---------------- flush: 1bpp -> RGB565 bands -> LcdDraw ---------------- */

static void ui_flush(void)
{
    for (int y0 = 0; y0 < UI_FB_H; y0 += UI_BAND_ROWS) {
        uint8_t *p = g_band;

        /* The DMA reads g_band directly: never refill the buffer while a
         * transfer is still in flight (band-tearing otherwise). */
        while (LcdBusy()) {
            osDelay(1);
        }

        for (int y = y0; y < y0 + UI_BAND_ROWS; y++) {
            const uint8_t *row = &g_fb[y * FB_STRIDE];
            for (int bx = 0; bx < FB_STRIDE; bx++) {
                uint8_t bits = row[bx];
                for (int bit = 0; bit < 8; bit++) {
                    uint16_t c = (bits & (0x80u >> bit)) ? UI_INK_RGB565 : UI_BG_RGB565;
                    *p++ = (uint8_t)(c >> 8);
                    *p++ = (uint8_t)(c & 0xFF);
                }
            }
        }

        LcdDraw(0, y0, UI_FB_W - 1, y0 + UI_BAND_ROWS - 1, (uint16_t *)g_band);
    }
    while (LcdBusy()) {
        osDelay(1);
    }
}

/* ---------------- page rendering ---------------- */

static void draw_button_label(int x0, int x1, const char *s)
{
    int w = text_w(s, UI_BTN_LABEL_SCALE);
    int h = UI_FONT_GLYPH_H * UI_BTN_LABEL_SCALE;
    int x = x0 + (x1 - x0 + 1 - w) / 2;
    int y = UI_BTN_Y0 + (UI_BTN_Y1 - UI_BTN_Y0 + 1 - h) / 2;

    draw_text(x, y, s, UI_BTN_LABEL_SCALE);
}

static void draw_footer(void)
{
    char line[64];

    /* Version string built from version.h macros directly: version.c's
     * helpers reference the keystone-era i18n `_()` function, which has no
     * implementation in this tree (dead code until referenced). */
    snprintf(line, sizeof(line), "fw v%d.%d.%d %s",
             SOFTWARE_VERSION_MAJOR - SOFTWARE_VERSION_MAJOR_OFFSET,
             SOFTWARE_VERSION_MINOR, SOFTWARE_VERSION_BUILD,
             FIRMWARE_GIT_HASH);
    draw_text(UI_FOOTER_X, UI_FOOTER_L1_Y, line, 1);

    if (g_touch_probe_addr == 0xFF) {
        snprintf(line, sizeof(line), "touch: not probed");
    } else if (g_touch_probe_ok) {
        snprintf(line, sizeof(line), "touch 0x%02X ok=1", g_touch_probe_addr);
    } else {
        snprintf(line, sizeof(line), "touch none 0x%02X", g_touch_probe_addr);
    }
    draw_text(UI_FOOTER_X, UI_FOOTER_L2_Y, line, 1);

    draw_text(UI_FOOTER_X, UI_FOOTER_L3_Y, g_last, 1);
}

static void draw_page(void)
{
    memset(g_fb, 0, FB_BYTES);

    if (g_page == PAGE_WELCOME) {
        draw_text_center(UI_W_TITLE_Y, UI_TXT_TITLE, UI_W_TITLE_SCALE);
        draw_text_center(UI_W_SUB_Y, UI_TXT_SUB, UI_W_SUB_SCALE);
        draw_text_center(UI_W_BIG_Y, UI_TXT_BIG, UI_W_BIG_SCALE);
        draw_text_center(UI_W_HINT_Y, UI_TXT_HINT, UI_W_HINT_SCALE);
    } else {
        draw_text_center(UI_S_TITLE_Y, UI_TXT_SCAN, UI_S_TITLE_SCALE);
        draw_text_center(UI_S_SUB_Y, UI_TXT_SCAN_SUB, UI_S_SUB_SCALE);
        rect_outline(UI_S_BOX_X0, UI_S_BOX_Y0, UI_S_BOX_X1, UI_S_BOX_Y1, UI_S_BOX_T);
        draw_text_center(UI_S_NOTE_Y, UI_TXT_SCAN_NOTE, UI_S_NOTE_SCALE);
    }

    fill_rect(UI_LINE_X0, UI_LINE_Y, UI_LINE_X1 - UI_LINE_X0 + 1, 1);

    rect_outline(UI_BTN_L_X0, UI_BTN_Y0, UI_BTN_L_X1, UI_BTN_Y1, UI_BTN_T);
    rect_outline(UI_BTN_R_X0, UI_BTN_Y0, UI_BTN_R_X1, UI_BTN_Y1, UI_BTN_T);
    draw_button_label(UI_BTN_L_X0, UI_BTN_L_X1, UI_BTN_LABEL_LEFT);
    draw_button_label(UI_BTN_R_X0, UI_BTN_R_X1, UI_BTN_LABEL_RIGHT);

    draw_footer();
}

/* ---------------- input ---------------- */

static void handle_press(int x, int y)
{
    int on_back = (y >= UI_BTN_Y0 && y <= UI_BTN_Y1 &&
                   x >= UI_BTN_L_X0 && x <= UI_BTN_L_X1);
    int on_cont = (y >= UI_BTN_Y0 && y <= UI_BTN_Y1 &&
                   x >= UI_BTN_R_X0 && x <= UI_BTN_R_X1);

    if (on_back) {
        if (g_page == PAGE_SCAN) {
            g_page = PAGE_WELCOME;
            snprintf(g_last, sizeof(g_last), "last: back -> welcome (%d,%d)", x, y);
        } else {
            snprintf(g_last, sizeof(g_last), "last: back (noop) (%d,%d)", x, y);
        }
    } else if (on_cont) {
        if (g_page == PAGE_WELCOME) {
            g_page = PAGE_SCAN;
            snprintf(g_last, sizeof(g_last), "last: continue -> scan (%d,%d)", x, y);
        } else {
            snprintf(g_last, sizeof(g_last), "last: continue (scan stub) (%d,%d)", x, y);
        }
    } else {
        snprintf(g_last, sizeof(g_last), "last: tap (%d,%d)", x, y);
    }

    printf("ui: %s\r\n", g_last);
    draw_page();
    ui_flush();
}

/* ---------------- public API ---------------- */

void UiInit(void)
{
    g_fb = SramMalloc(FB_BYTES);
    g_band = SramMalloc(UI_BAND_BYTES);
    if (g_fb == NULL || g_band == NULL) {
        /* Cannot render. Stay alive (the task keeps feeding the WDT) so the
         * failure is diagnosable instead of a reset loop; screen stays black. */
        printf("ui: alloc failed fb=%p band=%p\r\n", (void *)g_fb, (void *)g_band);
        return;
    }
    memset(g_fb, 0, FB_BYTES);
    printf("ui: fb=%u B band=%u B\r\n", (unsigned)FB_BYTES, (unsigned)UI_BAND_BYTES);
}

void UiShow(void)
{
    if (g_fb == NULL || g_band == NULL) {
        return;
    }
    draw_page();
    ui_flush();
}

void UiTick(void)
{
    static int prev_down = 0;
    TouchStatus_t st;

    if (g_fb == NULL) {
        return;
    }
    if (TouchGetStatus(&st) != 0) {
        prev_down = 0;
        return;
    }

    int down = st.touch ? 1 : 0;
    if (down && !prev_down) {
        handle_press((int)st.x, (int)st.y);
    }
    prev_down = down;
}
