/* shlosilo_ui.c - product UI: direct-write 1bpp renderer + touch buttons.
 *
 * The forgebox product line owns the panel with this module - no LVGL.
 * LVGL stays as the bring-up diagnostics renderer behind the SMOKE_SCREEN
 * build switch (exactly one renderer owns the screen per build).
 *
 * Model: a 1bpp canvas (480x800 = 46.9 KiB, SRAM heap) holds the current
 * frame; ui_flush_range() expands it to RGB565 rows in a band buffer and
 * streams each band through LcdDraw() (8080-parallel DMA). Text uses the
 * Terminus 8x16 blob (ui_font.c), byte-identical to the pico2 host's font.
 * Layout constants live in ui_layout.h (shared with the host preview script).
 *
 * Pages:
 *  - welcome: title + hint, back/continue buttons.
 *  - scan:    camera QR scan status; the product task owns the scan loop and
 *             pushes live lines in through UiScanInfo()/UiScanProgress()
 *             (partial flush of the live region only, so scanning keeps its
 *             frame rate).
 *  - payload: a decoded QR payload rendered with word wrap.
 *
 * Touch: FT6336 polled via TouchGetStatus(), press-edge detection, two text
 * buttons (`back` left / `continue` right). Every press echoes on the footer
 * line and in the printf log. The footer also carries the build identity
 * (git hash) and the touch probe state - the on-screen diagnostic channel
 * that replaces a console.
 */
#include "shlosilo_ui.h"
#include "ui_layout.h"
#include "ui_font.h"
#include "ui_wrap.h"
#include "ui_qr.h"
#include "hal_lcd.h"
#include "hal_touch.h"
#include "user_memory.h"
#include "version.h"
#include "cmsis_os.h"
#include <stdio.h>
#include <string.h>

/* fw_identity.h is generated by CMake at configure time (build dir):
 *     #define FIRMWARE_GIT_HASH "<short-hash>[-dirty]"  */
#include "fw_identity.h"

#ifndef FIRMWARE_GIT_HASH
#define FIRMWARE_GIT_HASH "dev"
#endif

#define FB_STRIDE  (UI_FB_W / 8)
#define FB_BYTES   (FB_STRIDE * UI_FB_H)

/* Flush band height; UI_FB_H must be a multiple of this. */
#define UI_BAND_ROWS  40
#define UI_BAND_BYTES (UI_FB_W * UI_BAND_ROWS * 2)

#define LIVE_LINE_BYTES 40

/* Input poll hook (see shlosilo_ui.h): invoked from every synchronous wait
 * so the product task keeps sampling touch while the UI is blocked. */
static UiInputPollFn s_input_poll;

void UiSetInputPoll(UiInputPollFn fn)
{
    s_input_poll = fn;
}

void UiInputPoll(void)
{
    if (s_input_poll != NULL) {
        s_input_poll();
    }
}

static uint8_t *g_fb;
static uint8_t *g_band;
static UiPage g_page = UI_PAGE_WELCOME;
static char g_last[64] = "last: -";
static int g_touch_prev_down;

/* Scan page live lines (status + three small lines), pushed by the caller. */
static char g_scan_l1[LIVE_LINE_BYTES] = "";
static char g_scan_l2[LIVE_LINE_BYTES] = "";
static char g_scan_l3[LIVE_LINE_BYTES] = "";
static char g_scan_l4[LIVE_LINE_BYTES] = "";
static uint8_t g_scan_progress;

/* Payload page text (copied from the caller's buffer). */
#define PAYLOAD_MAX 2048
static char g_payload[PAYLOAD_MAX];
static uint32_t g_payload_len;

/* UR carousel page: qrcodegen scratch + result buffers (lazy, SRAM heap). */
static uint8_t *g_qr_temp;
static uint8_t *g_qr_code;

/* ---------------- canvas primitives (inclusive coordinates) ---------------- */

static void put_px(int x, int y)
{
    if ((unsigned)x < UI_FB_W && (unsigned)y < UI_FB_H) {
        g_fb[y * FB_STRIDE + (x >> 3)] |= (uint8_t)(0x80u >> (x & 7));
    }
}

static void fill_rect(int x, int y, int w, int h)
{
    for (int yy = y; yy < y + h; yy++) {
        for (int xx = x; xx < x + w; xx++) {
            put_px(xx, yy);
        }
    }
}

static void clear_rect(int x, int y, int w, int h)
{
    for (int yy = y; yy < y + h; yy++) {
        for (int xx = x; xx < x + w; xx++) {
            if ((unsigned)xx < UI_FB_W && (unsigned)yy < UI_FB_H) {
                g_fb[yy * FB_STRIDE + (xx >> 3)] &= (uint8_t)~(0x80u >> (xx & 7));
            }
        }
    }
}

static void rect_outline(int x0, int y0, int x1, int y1, int t)
{
    for (int k = 0; k < t; k++) {
        fill_rect(x0 + k, y0 + k, x1 - x0 - 2 * k + 1, 1);
        fill_rect(x0 + k, y1 - k, x1 - x0 - 2 * k + 1, 1);
        fill_rect(x0 + k, y0 + k, 1, y1 - y0 - 2 * k + 1);
        fill_rect(x1 - k, y0 + k, 1, y1 - y0 - 2 * k + 1);
    }
}

static int text_w(const char *s, int scale)
{
    return (int)strlen(s) * UI_FONT_GLYPH_W * scale;
}

static void draw_text(int x, int y, const char *s, int scale)
{
    for (const char *p = s; *p != '\0'; p++) {
        int c = (unsigned char)*p;
        const uint8_t *g = ui_font_8x16[(c >= 0x20 && c <= 0x7E) ? (c - 0x20)
                                                                : ('?' - 0x20)];
        for (int row = 0; row < UI_FONT_GLYPH_H; row++) {
            uint8_t bits = g[row];
            if (bits == 0) {
                continue;
            }
            for (int col = 0; col < UI_FONT_GLYPH_W; col++) {
                if (bits & (0x80u >> col)) {
                    fill_rect(x + col * scale, y + row * scale, scale, scale);
                }
            }
        }
        x += UI_FONT_GLYPH_W * scale;
    }
}

static void draw_text_center(int y, const char *s, int scale)
{
    draw_text((UI_FB_W - text_w(s, scale)) / 2, y, s, scale);
}

/* ---------------- flush: 1bpp -> RGB565 bands -> LcdDraw ---------------- */

static void ui_flush_range(int y0, int y1)
{
    if (g_fb == NULL || g_band == NULL || y1 < y0) {
        return;
    }

    /* Snap to band boundaries (UI_FB_H is a multiple of UI_BAND_ROWS). */
    y0 -= y0 % UI_BAND_ROWS;
    y1 = (y1 / UI_BAND_ROWS + 1) * UI_BAND_ROWS - 1;
    if (y1 >= UI_FB_H) {
        y1 = UI_FB_H - 1;
    }

    for (int ys = y0; ys <= y1; ys += UI_BAND_ROWS) {
        uint8_t *p = g_band;

        /* The DMA reads g_band directly: never refill the buffer while a
         * transfer is still in flight (band-tearing otherwise). Input stays
         * live through the flush: poll in the wait loop (~1 ms cadence) and
         * once per band. */
        while (LcdBusy()) {
            UiInputPoll();
            osDelay(1);
        }
        UiInputPoll();

        for (int y = ys; y < ys + UI_BAND_ROWS; y++) {
            const uint8_t *row = &g_fb[y * FB_STRIDE];
            for (int bx = 0; bx < FB_STRIDE; bx++) {
                uint8_t bits = row[bx];
                for (int bit = 0; bit < 8; bit++) {
                    uint16_t c = (bits & (0x80u >> bit)) ? UI_INK_RGB565 : UI_BG_RGB565;
                    *p++ = (uint8_t)(c >> 8);
                    *p++ = (uint8_t)(c & 0xFF);
                }
            }
        }

        LcdDraw(0, ys, UI_FB_W - 1, ys + UI_BAND_ROWS - 1, (uint16_t *)g_band);
    }
    while (LcdBusy()) {
        UiInputPoll();
        osDelay(1);
    }
}

/* ---------------- scan page live region ---------------- */

static void scan_live_rect_clear(void)
{
    int x0 = UI_S_BOX_X0 + UI_S_BOX_T;
    int x1 = UI_S_BOX_X1 - UI_S_BOX_T;
    int y0 = UI_S_STATUS_Y - 4;
    int y1 = UI_S_INFO3_Y + UI_FONT_GLYPH_H - 1;

    clear_rect(x0, y0, x1 - x0 + 1, y1 - y0 + 1);
}

static void draw_scan_live(void)
{
    char status[LIVE_LINE_BYTES];

    if (g_scan_progress > 0) {
        snprintf(status, sizeof(status), "scanning %u%%", (unsigned)g_scan_progress);
    } else {
        snprintf(status, sizeof(status), "%s", g_scan_l1);
    }
    draw_text_center(UI_S_STATUS_Y, status, UI_S_STATUS_SCALE);
    draw_text(UI_S_INFO_X, UI_S_INFO1_Y, g_scan_l2, 1);
    draw_text(UI_S_INFO_X, UI_S_INFO2_Y, g_scan_l3, 1);
    draw_text(UI_S_INFO_X, UI_S_INFO3_Y, g_scan_l4, 1);
}

static void scan_live_update(void)
{
    if (g_page != UI_PAGE_SCAN || g_fb == NULL || g_band == NULL) {
        return;
    }
    scan_live_rect_clear();
    draw_scan_live();
    ui_flush_range(UI_S_STATUS_Y - 4, UI_S_INFO3_Y + UI_FONT_GLYPH_H - 1);
}

/* ---------------- scan preview: binarized camera view (D2.1) ---------------- */

#define PV_SRC_W   640
#define PV_SRC_H   480
#define PV_BLK     8
#define PV_BW      (PV_SRC_W / PV_BLK)      /* 80 block columns */
#define PV_BH      (PV_SRC_H / PV_BLK)      /* 60 block rows */
#define PV_MARGIN  6                        /* luma levels */

#if ((UI_S_PV_X0 % 8) != 0) || ((UI_S_PV_W % 8) != 0)
#error "scan preview region must be byte-aligned on the 1bpp canvas"
#endif

static uint16_t s_pv_block[PV_BW * PV_BH];  /* per-block local means, 9.6 KiB */
static uint32_t s_pv_focus;                 /* sharpness score of the last frame */

static void toggle_px(int x, int y)
{
    if ((unsigned)x < UI_FB_W && (unsigned)y < UI_FB_H) {
        g_fb[y * FB_STRIDE + (x >> 3)] ^= (uint8_t)(0x80u >> (x & 7));
    }
}

static void draw_scan_reticle(void)
{
    int cx = UI_S_PV_X0 + UI_S_PV_W / 2;
    int cy = UI_S_PV_Y0 + UI_S_PV_H / 2;

    /* XOR so the cross stays visible on both dark background and lit modules.
     * Long arms: when the QR is close (filling the view) the arm still
     * reaches the dark background around it. */
    for (int d = 4; d <= 28; d++) {
        toggle_px(cx - d, cy);
        toggle_px(cx + d, cy);
        toggle_px(cx, cy - d);
        toggle_px(cx, cy + d);
    }
}

/* Central-region gradient energy (sampled): rises as the image sharpens -
 * use it to pick the working distance (same idea as the pico2 focus score). */
static uint32_t scan_focus_score(const uint8_t *gray)
{
    uint32_t sum = 0, cnt = 0;

    for (int y = 120; y <= 355; y += 4) {
        const uint8_t *row = gray + y * PV_SRC_W;
        for (int x = 160; x <= 472; x += 4) {
            int gx = (int)row[x + 4] - (int)row[x];
            int gy = (int)row[x] - (int)row[x + 4 * PV_SRC_W];
            sum += (uint32_t)((gx < 0 ? -gx : gx) + (gy < 0 ? -gy : gy));
            cnt++;
        }
    }
    return cnt ? (sum / cnt) : 0;
}

void UiScanPreview(const uint8_t *gray, int w, int h)
{
    if (g_page != UI_PAGE_SCAN || g_fb == NULL || g_band == NULL) {
        return;
    }
    if (gray == NULL || w != PV_SRC_W || h != PV_SRC_H) {
        return;
    }

    /* Pass 1: per-block local means (8x8 source pixels -> 80x60 grid). */
    for (int by = 0; by < PV_BH; by++) {
        for (int bx = 0; bx < PV_BW; bx++) {
            uint32_t sum = 0;
            for (int yy = 0; yy < PV_BLK; yy++) {
                const uint8_t *p = gray + (by * PV_BLK + yy) * PV_SRC_W + bx * PV_BLK;
                for (int xx = 0; xx < PV_BLK; xx++) {
                    sum += p[xx];
                }
            }
            s_pv_block[by * PV_BW + bx] = (uint16_t)(sum >> 6);
        }
    }

    /* Pass 2: 2x2 downsample + local threshold -> 1bpp, one byte per 8 px.
     * Lit = darker than the local mean: QR modules show lit on black, the
     * same convention the pico2 host's binarized view uses. */
    for (int py = 0; py < UI_S_PV_H; py++) {
        const uint8_t *r0 = gray + (py * 2) * PV_SRC_W;
        const uint8_t *r1 = r0 + PV_SRC_W;
        const uint16_t *bm = s_pv_block + (py >> 2) * PV_BW;
        uint8_t *dst = g_fb + (UI_S_PV_Y0 + py) * FB_STRIDE + (UI_S_PV_X0 >> 3);
        int px = 0;

        for (int bi = 0; bi < UI_S_PV_W / 8; bi++) {
            uint8_t bits = 0;
            for (int k = 0; k < 8; k++, px++) {
                const uint8_t *p0 = r0 + px * 2;
                const uint8_t *p1 = r1 + px * 2;
                int avg = ((int)p0[0] + p0[1] + p1[0] + p1[1]) >> 2;
                int mean = (int)bm[px >> 2];
                if (avg + PV_MARGIN < mean) {
                    bits |= (uint8_t)(0x80u >> k);
                }
            }
            *dst++ = bits;
        }
    }

    s_pv_focus = scan_focus_score(gray);
    draw_scan_reticle();
    /* 1px frame marking the camera view area (the preview has no natural edge). */
    rect_outline(UI_S_PV_X0 - 1, UI_S_PV_Y0 - 1,
                 UI_S_PV_X0 + UI_S_PV_W, UI_S_PV_Y0 + UI_S_PV_H, 1);
    ui_flush_range(UI_S_PV_Y0, UI_S_PV_Y0 + UI_S_PV_H - 1);
}

uint32_t UiScanGetFocus(void)
{
    return s_pv_focus;
}

/* ---------------- payload page ---------------- */

static void draw_payload_text(void)
{
    UiWrapLine lines[UI_P_MAX_LINES];
    bool truncated = false;
    int count = ui_wrap_text(g_payload, g_payload_len, UI_P_CHARS_PER_LINE,
                             UI_P_MAX_LINES, lines, &truncated);
    int y = UI_P_TEXT_Y0;

    for (int i = 0; i < count; i++) {
        char buf[UI_P_CHARS_PER_LINE + 1];
        uint32_t len = lines[i].len;

        if (len > UI_P_CHARS_PER_LINE) {
            len = UI_P_CHARS_PER_LINE;
        }
        memcpy(buf, &g_payload[lines[i].start], len);
        buf[len] = '\0';
        draw_text(UI_P_TEXT_X, y, buf, 1);
        y += UI_P_LINE_H;
    }

    if (truncated) {
        draw_text(UI_P_TEXT_X, y, "...", 1);
    }
}

/* ---------------- page rendering ---------------- */

static void draw_button_label(int x0, int x1, const char *s)
{
    int w = text_w(s, UI_BTN_LABEL_SCALE);
    int h = UI_FONT_GLYPH_H * UI_BTN_LABEL_SCALE;
    int x = x0 + (x1 - x0 + 1 - w) / 2;
    int y = UI_BTN_Y0 + (UI_BTN_Y1 - UI_BTN_Y0 + 1 - h) / 2;

    draw_text(x, y, s, UI_BTN_LABEL_SCALE);
}

static void draw_footer(void)
{
    char line[64];

    /* Version string built from version.h macros directly: version.c's
     * helpers reference the keystone-era i18n `_()` function, which has no
     * implementation in this tree (dead code until referenced). */
    snprintf(line, sizeof(line), "fw v%d.%d.%d %s",
             SOFTWARE_VERSION_MAJOR - SOFTWARE_VERSION_MAJOR_OFFSET,
             SOFTWARE_VERSION_MINOR, SOFTWARE_VERSION_BUILD,
             FIRMWARE_GIT_HASH);
    draw_text(UI_FOOTER_X, UI_FOOTER_L1_Y, line, 1);

    if (g_touch_probe_addr == 0xFF) {
        snprintf(line, sizeof(line), "touch: not probed");
    } else if (g_touch_probe_ok) {
        snprintf(line, sizeof(line), "touch 0x%02X ok=1", g_touch_probe_addr);
    } else {
        snprintf(line, sizeof(line), "touch none 0x%02X", g_touch_probe_addr);
    }
    draw_text(UI_FOOTER_X, UI_FOOTER_L2_Y, line, 1);

    draw_text(UI_FOOTER_X, UI_FOOTER_L3_Y, g_last, 1);
}

static void draw_page(void)
{
    memset(g_fb, 0, FB_BYTES);

    switch (g_page) {
    case UI_PAGE_WELCOME:
        draw_text_center(UI_W_TITLE_Y, UI_TXT_TITLE, UI_W_TITLE_SCALE);
        draw_text_center(UI_W_SUB_Y, UI_TXT_SUB, UI_W_SUB_SCALE);
        draw_text_center(UI_W_BIG_Y, UI_TXT_BIG, UI_W_BIG_SCALE);
        draw_text_center(UI_W_HINT_Y, UI_TXT_HINT, UI_W_HINT_SCALE);
        break;

    case UI_PAGE_SCAN:
        draw_text_center(UI_S_TITLE_Y, UI_TXT_SCAN, UI_S_TITLE_SCALE);
        draw_text_center(UI_S_SUB_Y, UI_TXT_SCAN_SUB, UI_S_SUB_SCALE);
        rect_outline(UI_S_BOX_X0, UI_S_BOX_Y0, UI_S_BOX_X1, UI_S_BOX_Y1, UI_S_BOX_T);
        scan_live_rect_clear();
        draw_scan_live();
        break;

    case UI_PAGE_PAYLOAD: {
        char info[48];
        draw_text_center(UI_P_TITLE_Y, UI_TXT_RESULT, UI_P_TITLE_SCALE);
        snprintf(info, sizeof(info), "%u chars", (unsigned)g_payload_len);
        draw_text_center(UI_P_INFO_Y, info, 1);
        draw_payload_text();
        break;
    }

    case UI_PAGE_QR:
        /* Placeholder until the first carousel frame arrives. */
        draw_text_center(UI_Q_TITLE_Y, UI_Q_TXT_TITLE, UI_Q_TITLE_SCALE);
        draw_text_center(UI_Q_AREA_Y0 + UI_Q_AREA_H / 2, "preparing...", 2);
        break;

    default:
        break;
    }

    fill_rect(UI_LINE_X0, UI_LINE_Y, UI_LINE_X1 - UI_LINE_X0 + 1, 1);

    rect_outline(UI_BTN_L_X0, UI_BTN_Y0, UI_BTN_L_X1, UI_BTN_Y1, UI_BTN_T);
    rect_outline(UI_BTN_R_X0, UI_BTN_Y0, UI_BTN_R_X1, UI_BTN_Y1, UI_BTN_T);
    draw_button_label(UI_BTN_L_X0, UI_BTN_L_X1, UI_BTN_LABEL_LEFT);
    draw_button_label(UI_BTN_R_X0, UI_BTN_R_X1, UI_BTN_LABEL_RIGHT);

    draw_footer();
}

void UiShowQrFrame(const char *text, uint32_t index, uint32_t total)
{
    char cap[48];
    int modules = 0;
    UiQrLayout layout;

    if (g_fb == NULL || g_band == NULL || text == NULL) {
        return;
    }
    if (g_qr_temp == NULL) {
        g_qr_temp = SramMalloc(UI_QR_BUF_BYTES);
        g_qr_code = SramMalloc(UI_QR_BUF_BYTES);
        if (g_qr_temp == NULL || g_qr_code == NULL) {
            printf("ui: qr buffers alloc failed\r\n");
        }
    }

    memset(g_fb, 0, FB_BYTES);

    if (g_qr_temp == NULL || g_qr_code == NULL ||
            !ui_qr_encode(text, g_qr_temp, g_qr_code, &modules) ||
            !ui_qr_layout(modules, UI_Q_AREA_X0, UI_Q_AREA_Y0,
                          UI_Q_AREA_W, UI_Q_AREA_H, &layout)) {
        draw_text_center(UI_Q_AREA_Y0 + UI_Q_AREA_H / 2, "qr encode FAIL", 2);
    } else {
        ui_qr_draw(g_qr_code, &layout, g_fb, UI_FB_W, UI_FB_H);
        draw_text_center(UI_Q_TITLE_Y, UI_Q_TXT_TITLE, UI_Q_TITLE_SCALE);
        snprintf(cap, sizeof(cap), "ur frame %u/%u",
                 (unsigned)index + 1, (unsigned)total);
        draw_text_center(UI_Q_CAP_Y, cap, 1);
    }

    /* One poll between the encode/draw work and the flush: the flush itself
     * polls too (UiInputPoll in ui_flush_range). */
    UiInputPoll();

    fill_rect(UI_LINE_X0, UI_LINE_Y, UI_LINE_X1 - UI_LINE_X0 + 1, 1);
    rect_outline(UI_BTN_L_X0, UI_BTN_Y0, UI_BTN_L_X1, UI_BTN_Y1, UI_BTN_T);
    rect_outline(UI_BTN_R_X0, UI_BTN_Y0, UI_BTN_R_X1, UI_BTN_Y1, UI_BTN_T);
    draw_button_label(UI_BTN_L_X0, UI_BTN_L_X1, UI_BTN_LABEL_LEFT);
    draw_button_label(UI_BTN_R_X0, UI_BTN_R_X1, UI_BTN_LABEL_RIGHT);
    draw_footer();

    ui_flush_range(0, UI_FB_H - 1);
}

/* ---------------- panic ---------------- */

void UiPanic(const char *msg)
{
    UiWrapLine lines[12];
    bool truncated = false;
    uint32_t len;
    int count;
    int y = 200;

    if (g_fb == NULL || g_band == NULL || msg == NULL) {
        return;
    }
    memset(g_fb, 0, FB_BYTES);
    draw_text_center(72, "PANIC", 3);

    len = (uint32_t)strlen(msg);
    count = ui_wrap_text(msg, len, 56, 12, lines, &truncated);
    for (int i = 0; i < count; i++) {
        char buf[57];
        uint32_t n = lines[i].len;

        if (n > 56) {
            n = 56;
        }
        memcpy(buf, &msg[lines[i].start], n);
        buf[n] = '\0';
        draw_text(16, y, buf, 1);
        y += 18;
    }
    if (truncated) {
        draw_text(16, y, "...", 1);
    }

    draw_footer();
    ui_flush_range(0, UI_FB_H - 1);
}

/* ---------------- input ---------------- */

bool UiIsBackButton(int x, int y)
{
    return (y >= UI_BTN_Y0 && y <= UI_BTN_Y1 &&
            x >= UI_BTN_L_X0 && x <= UI_BTN_L_X1);
}

bool UiIsContinueButton(int x, int y)
{
    return (y >= UI_BTN_Y0 && y <= UI_BTN_Y1 &&
            x >= UI_BTN_R_X0 && x <= UI_BTN_R_X1);
}

void UiSetLast(const char *text)
{
    snprintf(g_last, sizeof(g_last), "last: %.50s", text ? text : "-");
}

static void handle_press(int x, int y)
{
    char msg[56];

    if (UiIsBackButton(x, y)) {
        if (g_page == UI_PAGE_WELCOME) {
            /* Dev entry (F3 output side): welcome back -> UR carousel demo. */
            snprintf(msg, sizeof(msg), "back -> ur demo (%d,%d)", x, y);
            g_page = UI_PAGE_QR;
        } else {
            snprintf(msg, sizeof(msg), "back -> welcome (%d,%d)", x, y);
            g_page = UI_PAGE_WELCOME;
        }
    } else if (UiIsContinueButton(x, y)) {
        if (g_page == UI_PAGE_WELCOME || g_page == UI_PAGE_PAYLOAD) {
            snprintf(msg, sizeof(msg), "continue -> scan (%d,%d)", x, y);
            g_page = UI_PAGE_SCAN;
        } else {
            snprintf(msg, sizeof(msg), "continue (scan) (%d,%d)", x, y);
        }
    } else {
        snprintf(msg, sizeof(msg), "tap (%d,%d)", x, y);
    }

    UiSetLast(msg);
    printf("ui: %s\r\n", g_last);
    draw_page();
    ui_flush_range(0, UI_FB_H - 1);
}

/* ---------------- public API ---------------- */

void UiInit(void)
{
    g_fb = SramMalloc(FB_BYTES);
    g_band = SramMalloc(UI_BAND_BYTES);
    if (g_fb == NULL || g_band == NULL) {
        /* Cannot render. Stay alive (the task keeps feeding the WDT) so the
         * failure is diagnosable instead of a reset loop; screen stays black. */
        printf("ui: alloc failed fb=%p band=%p\r\n", (void *)g_fb, (void *)g_band);
        return;
    }
    memset(g_fb, 0, FB_BYTES);
    printf("ui: fb=%u B band=%u B\r\n", (unsigned)FB_BYTES, (unsigned)UI_BAND_BYTES);
}

void UiShow(void)
{
    if (g_fb == NULL || g_band == NULL) {
        return;
    }
    draw_page();
    ui_flush_range(0, UI_FB_H - 1);
}

void UiTick(void)
{
    TouchStatus_t st;

    if (g_fb == NULL) {
        return;
    }
    if (TouchGetStatus(&st) != 0) {
        g_touch_prev_down = 0;
        return;
    }

    int down = st.touch ? 1 : 0;
    if (down && !g_touch_prev_down) {
        handle_press((int)st.x, (int)st.y);
    }
    g_touch_prev_down = down;
}

UiPage UiGetPage(void)
{
    return g_page;
}

void UiGotoPage(UiPage page)
{
    g_page = page;
    if (g_fb == NULL || g_band == NULL) {
        return;
    }
    draw_page();
    ui_flush_range(0, UI_FB_H - 1);
}

void UiSetPayload(const char *text, uint32_t len)
{
    uint32_t n = len;

    if (n > sizeof(g_payload) - 1) {
        n = sizeof(g_payload) - 1;
    }
    if (text != NULL && n > 0) {
        memcpy(g_payload, text, n);
    }
    g_payload[n] = '\0';
    g_payload_len = n;

    UiGotoPage(UI_PAGE_PAYLOAD);
}

void UiScanInfo(const char *line1, const char *line2, const char *line3, const char *line4)
{
    snprintf(g_scan_l1, sizeof(g_scan_l1), "%s", line1 ? line1 : "");
    snprintf(g_scan_l2, sizeof(g_scan_l2), "%s", line2 ? line2 : "");
    snprintf(g_scan_l3, sizeof(g_scan_l3), "%s", line3 ? line3 : "");
    snprintf(g_scan_l4, sizeof(g_scan_l4), "%s", line4 ? line4 : "");
    scan_live_update();
}

void UiScanProgress(uint8_t percent)
{
    g_scan_progress = percent;
    scan_live_update();
}

void UiTouchReset(void)
{
    /* Treat the current contact as already seen: no action until the finger
     * is lifted and pressed again. */
    g_touch_prev_down = 1;
}
