/* ui_font.h - generated by flux/forgebox/scripts/convert_font.py.
 * DO NOT EDIT BY HAND; regenerate with:
 *     python3 flux/forgebox/scripts/convert_font.py */
#ifndef SHLOSILO_UI_FONT_H
#define SHLOSILO_UI_FONT_H

#include <stdint.h>

#define UI_FONT_GLYPH_W     8
#define UI_FONT_GLYPH_H     16
#define UI_FONT_GLYPHS      95  /* printable ASCII 0x20..0x7E */
#define UI_FONT_GLYPH_BYTES 16

extern const uint8_t ui_font_8x16[UI_FONT_GLYPHS][UI_FONT_GLYPH_BYTES];

#endif
