[package]
name = "shlosilo-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.shlosilo]
path = ".."

[[bin]]
name = "parse_psbt"
path = "fuzz_targets/parse_psbt.rs"
test = false
doc = false

[[bin]]
name = "xmr_unsigned_txset"
path = "fuzz_targets/xmr_unsigned_txset.rs"
test = false
doc = false
bench = false

[[bin]]
name = "multipart_decoder"
path = "fuzz_targets/multipart_decoder.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cbor_eth_sign"
path = "fuzz_targets/cbor_eth_sign.rs"
test = false
doc = false
bench = false
