#!/usr/bin/env python3
"""Regenerate the forgebox product-UI font tables from the pico2 Rust font.

Source of truth: `flux/pico2/src/font.rs` (Terminus 8x16, Lat15-Terminus16
PSF1 console font by Dimitar Zhekov, SIL OFL 1.1; printable ASCII 0x20..0x7E,
16 bytes per glyph, one byte per pixel row, MSB = leftmost pixel).

Outputs (both tracked files, checked in):
  flux/forgebox/src/ui/ui_font.h
  flux/forgebox/src/ui/ui_font.c

The font blob is byte-identical across hosts (pico2/font.rs is the canonical
copy); this script only re-encodes it as C. When the system console font
`/usr/share/consolefonts/Lat15-Terminus16.psf.gz` is present, the extracted
data is cross-checked against it (strongest provenance: pico2 font.rs -> PSF).

Usage (from anywhere):
    python3 flux/forgebox/scripts/convert_font.py [--check]

--check regenerates in memory and verifies the tracked files already match
(no writes; exit 1 on drift) — for CI / discipline.
"""

import argparse
import gzip
import hashlib
import re
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
FONT_RS = REPO / "flux/pico2/src/font.rs"
OUT_H = REPO / "flux/forgebox/src/ui/ui_font.h"
OUT_C = REPO / "flux/forgebox/src/ui/ui_font.c"
PSF_GZ = Path("/usr/share/consolefonts/Lat15-Terminus16.psf.gz")

FIRST, LAST = 0x20, 0x7E
COUNT = LAST - FIRST + 1
GLYPH_BYTES = 16


def parse_font_rs(path: Path) -> list[bytes]:
    text = path.read_text(encoding="utf-8")
    # Innermost bracketed blocks followed by a `// 0xNN` comment (cargo fmt
    # reflows the array into multi-line blocks, so match across lines).
    blocks = re.findall(r"\[([^\[\]]+)\]\s*,?\s*//\s*0x([0-9a-fA-F]{2})", text)
    glyphs: dict[int, bytes] = {}
    for content, code in blocks:
        c = int(code, 16)
        data = bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", content))
        if len(data) != GLYPH_BYTES:
            sys.exit(f"font.rs: glyph 0x{c:02X} has {len(data)} bytes, expected {GLYPH_BYTES}")
        if c in glyphs:
            sys.exit(f"font.rs: duplicate glyph 0x{c:02X}")
        glyphs[c] = data
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    extra = [c for c in glyphs if not (FIRST <= c <= LAST)]
    if missing or extra:
        sys.exit(f"font.rs: missing={missing} extra={extra}")
    return [glyphs[c] for c in range(FIRST, LAST + 1)]


def cross_check_psf(glyphs: list[bytes]) -> str:
    """Compare against the OS console font (authoritative). Returns a status line."""
    if not PSF_GZ.exists():
        return "PSF cross-check: skipped (system font not present)"
    raw = gzip.decompress(PSF_GZ.read_bytes())
    magic = struct.unpack_from("<H", raw, 0)[0]
    if magic != 0x0436:
        return f"PSF cross-check: skipped (unexpected magic 0x{magic:04X})"
    charsize = raw[3]
    if charsize != GLYPH_BYTES:
        return f"PSF cross-check: skipped (charsize {charsize})"
    mismatches = []
    for i, c in enumerate(range(FIRST, LAST + 1)):
        off = 4 + c * charsize
        if raw[off:off + charsize] != glyphs[i]:
            mismatches.append(f"0x{c:02X}")
    if mismatches:
        sys.exit(f"PSF cross-check FAILED for glyphs: {mismatches}")
    return f"PSF cross-check: OK ({COUNT} glyphs match Lat15-Terminus16.psf.gz)"


def render_c(glyphs: list[bytes]) -> str:
    lines = []
    lines.append("/* ui_font.c - generated by flux/forgebox/scripts/convert_font.py.")
    lines.append(" * DO NOT EDIT BY HAND; regenerate with:")
    lines.append(" *     python3 flux/forgebox/scripts/convert_font.py")
    lines.append(" *")
    lines.append(" * Terminus 8x16 (Lat15-Terminus16 PSF1 console font) by Dimitar")
    lines.append(" * Zhekov, SIL OFL 1.1. Printable ASCII 0x20..0x7E, 16 bytes per")
    lines.append(" * glyph, one byte per pixel row, MSB = leftmost pixel. The blob is")
    lines.append(" * byte-identical to flux/pico2/src/font.rs (canonical copy). */")
    lines.append('#include "ui_font.h"')
    lines.append("")
    lines.append("const uint8_t ui_font_8x16[UI_FONT_GLYPHS][UI_FONT_GLYPH_BYTES] = {")
    for i, c in enumerate(range(FIRST, LAST + 1)):
        data = glyphs[i]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"    {{ {hex_bytes} }}, /* 0x{c:02X} */")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def render_h() -> str:
    return "\n".join([
        "/* ui_font.h - generated by flux/forgebox/scripts/convert_font.py.",
        " * DO NOT EDIT BY HAND; regenerate with:",
        " *     python3 flux/forgebox/scripts/convert_font.py */",
        "#ifndef SHLOSILO_UI_FONT_H",
        "#define SHLOSILO_UI_FONT_H",
        "",
        "#include <stdint.h>",
        "",
        "#define UI_FONT_GLYPH_W     8",
        "#define UI_FONT_GLYPH_H     16",
        f"#define UI_FONT_GLYPHS      {COUNT}  /* printable ASCII 0x20..0x7E */",
        "#define UI_FONT_GLYPH_BYTES 16",
        "",
        "extern const uint8_t ui_font_8x16[UI_FONT_GLYPHS][UI_FONT_GLYPH_BYTES];",
        "",
        "#endif",
        "",
    ])


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify tracked files match; do not write")
    args = ap.parse_args()

    glyphs = parse_font_rs(FONT_RS)
    blob = b"".join(glyphs)
    print(f"font.rs: {COUNT} glyphs, {len(blob)} bytes, "
          f"sha256={hashlib.sha256(blob).hexdigest()}")
    print(cross_check_psf(glyphs))

    c_text, h_text = render_c(glyphs), render_h()
    if args.check:
        ok = True
        for path, text in ((OUT_H, h_text), (OUT_C, c_text)):
            cur = path.read_text(encoding="utf-8") if path.exists() else ""
            if cur.replace("\r\n", "\n") != text:
                print(f"DRIFT: {path}")
                ok = False
        sys.exit(0 if ok else 1)

    OUT_H.write_text(h_text, encoding="utf-8", newline="")
    OUT_C.write_text(c_text, encoding="utf-8", newline="")
    print(f"wrote {OUT_H.relative_to(REPO)}")
    print(f"wrote {OUT_C.relative_to(REPO)}")


if __name__ == "__main__":
    main()
