#!/usr/bin/env python3
"""Generate the QR self-test pattern for the forgebox scan diagnostic.

Writes flux/forgebox/src/driver/qr_selftest.c (a 21x21 version-1 QR module
matrix carrying "SELFTEST-OK", one uint32 per row) and verifies the pattern by
rendering it exactly as the firmware will stamp it (6 px/module, 4-module
quiet zone, dark=40 / light=190 luma) and decoding it with an independent
decoder (zxing-cpp). The same rendering is saved as PNG for the record.

Run: /tmp/qrvenv/bin/python3 flux/forgebox/scripts/gen_qr_selftest.py
"""
from pathlib import Path

import segno

REPO = Path(__file__).resolve().parents[3]
OUT_C = REPO / "flux/forgebox/src/driver/qr_selftest.c"
OUT_PNG = Path("/tmp/qr_selftest_pattern.png")

TEXT = "SELFTEST-OK"
MODULE_PX = 6
QUIET = 4
DARK = 40
LIGHT = 190

qr = segno.make(TEXT, error="m", micro=False)
matrix = qr.matrix
n = len(matrix)
assert n == 21, f"expected version-1 (21 modules), got {n}"

rows = []
for r in range(n):
    val = 0
    for c in range(n):
        if matrix[r][c]:
            val |= 1 << (n - 1 - c)
    rows.append(val)

lines = [f"    0x{rows[r]:07X}  /* row {r:2d} */" for r in range(n)]
body = ",\n".join(lines) + ","
c_text = f"""/* qr_selftest.c - synthetic QR pattern for the capture->decode self-test.
 *
 * Generated by flux/forgebox/scripts/gen_qr_selftest.py - do not hand-edit.
 * The pattern is a valid version-1 QR (ECC level M) carrying "{TEXT}".
 * drv_qrdecode.c stamps it into the completed capture buffer every few
 * frames so a decode that never happens on a real scene can be attributed:
 *   - self-test decodes  -> capture->decode path works end to end; the
 *     problem is the scene (distance / focus / framing).
 *   - self-test fails    -> pipeline problem (config / memory / flow).
 */
#include "qr_selftest.h"

/* One uint32 per row; bit (QR_SELFTEST_MODULES-1 - col) set = dark module. */
const uint32_t g_qr_selftest_modules[QR_SELFTEST_MODULES] = {{
{body}
}};

void QrSelfTestStamp(uint8_t *buf, int width, int height)
{{
    const int span = (QR_SELFTEST_MODULES + 2 * QR_SELFTEST_QUIET) * QR_SELFTEST_MODULE_PX;
    const int x0 = (width - span) / 2;
    const int y0 = (height - span) / 2;

    /* Quiet zone / light background over the whole stamp area. */
    for (int y = 0; y < span; y++) {{
        uint8_t *row = buf + (y0 + y) * width + x0;
        for (int x = 0; x < span; x++) {{
            row[x] = QR_SELFTEST_LIGHT;
        }}
    }}

    for (int r = 0; r < QR_SELFTEST_MODULES; r++) {{
        uint32_t bits = g_qr_selftest_modules[r];
        for (int c = 0; c < QR_SELFTEST_MODULES; c++) {{
            if (bits & (1u << (QR_SELFTEST_MODULES - 1 - c))) {{
                const int mx = x0 + (QR_SELFTEST_QUIET + c) * QR_SELFTEST_MODULE_PX;
                const int my = y0 + (QR_SELFTEST_QUIET + r) * QR_SELFTEST_MODULE_PX;
                for (int yy = 0; yy < QR_SELFTEST_MODULE_PX; yy++) {{
                    uint8_t *row = buf + (my + yy) * width + mx;
                    for (int xx = 0; xx < QR_SELFTEST_MODULE_PX; xx++) {{
                        row[xx] = QR_SELFTEST_DARK;
                    }}
                }}
            }}
        }}
    }}
}}
"""
OUT_C.write_text(c_text, encoding="utf-8", newline="\n")
print(f"wrote {OUT_C.relative_to(REPO)} ({len(c_text)} bytes, {n} rows)")

# --- verify: render exactly as the firmware stamps it and decode ---
from PIL import Image  # noqa: E402
import zxingcpp  # noqa: E402

span = (n + 2 * QUIET) * MODULE_PX
img = Image.new("L", (span, span), LIGHT)
px = img.load()
for r in range(n):
    for c in range(n):
        if matrix[r][c]:
            mx = (QUIET + c) * MODULE_PX
            my = (QUIET + r) * MODULE_PX
            for yy in range(MODULE_PX):
                for xx in range(MODULE_PX):
                    px[mx + xx, my + yy] = DARK
img.save(OUT_PNG)

res = zxingcpp.read_barcodes(img)
if res and res[0].text == TEXT:
    print(f"verify OK: independent decoder reads {res[0].text!r} from the stamp rendering "
          f"({span}x{span} px, {MODULE_PX} px/module)")
else:
    raise SystemExit(f"VERIFY FAILED: {res}")
