#!/usr/bin/env python3
"""Generate the QR self-test pattern for the forgebox scan diagnostic.

Writes flux/forgebox/src/driver/qr_selftest.c (a 21x21 version-1 QR module
matrix carrying "SELFTEST-OK", one uint32 per row + a stamping helper with a
runtime module size) and verifies the pattern by rendering it exactly as the
firmware stamps it (selectable px/module, 4-module quiet zone, dark=40 /
light=255 white background) and decoding it with an independent decoder
(zxing-cpp). The same rendering is saved as PNG for the record.

Run: /tmp/qrvenv/bin/python3 flux/forgebox/scripts/gen_qr_selftest.py
"""
from pathlib import Path

import segno

REPO = Path(__file__).resolve().parents[3]
OUT_C = REPO / "flux/forgebox/src/driver/qr_selftest.c"
OUT_PNG = Path("/tmp/qr_selftest_pattern.png")

TEXT = "SELFTEST-OK"
QUIET = 4
DARK = 40
LIGHT = 255

qr = segno.make(TEXT, error="m", micro=False)
matrix = qr.matrix
n = len(matrix)
assert n == 21, f"expected version-1 (21 modules), got {n}"

rows = []
for r in range(n):
    val = 0
    for c in range(n):
        if matrix[r][c]:
            val |= 1 << (n - 1 - c)
    rows.append(val)

lines = [f"    0x{rows[r]:07X}  /* row {r:2d} */" for r in range(n)]
body = ",\n".join(lines) + ","
c_text = f"""/* qr_selftest.c - synthetic QR pattern for the capture->decode self-test.
 *
 * Generated by flux/forgebox/scripts/gen_qr_selftest.py - do not hand-edit.
 * The pattern is a valid version-1 QR (ECC level M) carrying "{TEXT}".
 * drv_qrdecode.c stamps it into the completed capture buffer during the
 * diagnostic window so a decode that never happens on a real scene can be
 * attributed:
 *   - self-test decodes  -> capture->decode path works end to end; the
 *     problem is the scene (distance / focus / framing).
 *   - self-test fails    -> pipeline problem (config / memory / flow).
 *
 * The stamp paints a WHITE background over the whole frame and draws the
 * code with a runtime-selectable module size, giving the decode library the
 * easiest possible input (high contrast, big modules, clean quiet zone).
 * Diagnostic build only; not part of the product scan path.
 */
#include <string.h>
#include "qr_selftest.h"

/* One uint32 per row; bit (QR_SELFTEST_MODULES-1 - col) set = dark module. */
const uint32_t g_qr_selftest_modules[QR_SELFTEST_MODULES] = {{
{body}
}};

void QrSelfTestStamp(uint8_t *buf, int width, int height, int module_px)
{{
    const int span = (QR_SELFTEST_MODULES + 2 * QR_SELFTEST_QUIET) * module_px;
    const int x0 = (width - span) / 2;
    const int y0 = (height - span) / 2;

    if (module_px <= 0 || span > width || span > height) {{
        return;
    }}

    /* Whole frame white: the easiest possible background for binarization. */
    memset(buf, QR_SELFTEST_LIGHT, (size_t)width * (size_t)height);

    for (int r = 0; r < QR_SELFTEST_MODULES; r++) {{
        uint32_t bits = g_qr_selftest_modules[r];
        for (int c = 0; c < QR_SELFTEST_MODULES; c++) {{
            if (bits & (1u << (QR_SELFTEST_MODULES - 1 - c))) {{
                const int mx = x0 + (QR_SELFTEST_QUIET + c) * module_px;
                const int my = y0 + (QR_SELFTEST_QUIET + r) * module_px;
                for (int yy = 0; yy < module_px; yy++) {{
                    uint8_t *row = buf + (my + yy) * width + mx;
                    memset(row, QR_SELFTEST_DARK, (size_t)module_px);
                }}
            }}
        }}
    }}
}}
"""
OUT_C.write_text(c_text, encoding="utf-8", newline="\n")
print(f"wrote {OUT_C.relative_to(REPO)} ({len(c_text)} bytes, {n} rows)")

# --- verify: render exactly as the firmware stamps it and decode ---
from PIL import Image  # noqa: E402
import zxingcpp  # noqa: E402

ok = True
for module_px in (10, 16):
    span = (n + 2 * QUIET) * module_px
    img = Image.new("L", (640, 480), LIGHT)
    px = img.load()
    x0 = (640 - span) // 2
    y0 = (480 - span) // 2
    for r in range(n):
        for c in range(n):
            if matrix[r][c]:
                mx = x0 + (QUIET + c) * module_px
                my = y0 + (QUIET + r) * module_px
                for yy in range(module_px):
                    for xx in range(module_px):
                        px[mx + xx, my + yy] = DARK
    if module_px == 16:
        img.save(OUT_PNG)
    res = zxingcpp.read_barcodes(img)
    good = bool(res) and res[0].text == TEXT
    ok = ok and good
    print(f"module={module_px}px span={span}px: "
          f"{'OK ' + repr(res[0].text) if good else 'FAILED ' + repr(res)}")

if not ok:
    raise SystemExit("VERIFY FAILED")
print("verify OK: both stamp variants decode with an independent decoder")
