#!/usr/bin/env python3
"""Generate flux/forgebox/src/demo_payload.h from the signed txset fixture.

The UR carousel demo (F3 output side) plays this real signed txset as an
animated "xmr-txsigned" UR, exercising the output chain (encoder -> fountain
frames -> QR -> screen) before the full sign flow is assembled. Regenerate
after replacing the fixture:

Run: python3 flux/forgebox/scripts/gen_demo_payload.py
"""

import hashlib
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "tests/fixtures/signed_txset_1in_fresh.bin"
OUT = REPO / "flux/forgebox/src/demo_payload.h"

data = SRC.read_bytes()
digest = hashlib.sha256(data).hexdigest()

rows = []
for i in range(0, len(data), 16):
    chunk = data[i:i + 16]
    rows.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
body = "\n".join(rows)

text = f"""/* demo_payload.h - generated by flux/forgebox/scripts/gen_demo_payload.py.
 *
 * DO NOT EDIT BY HAND. Regenerate with:
 *     python3 flux/forgebox/scripts/gen_demo_payload.py
 *
 * Source: tests/fixtures/signed_txset_1in_fresh.bin
 *   {len(data)} bytes, sha256 {digest}
 * A real signed Monero txset (broadcast on mainnet; see the fixture README
 * in tests/fixtures/). The UR carousel demo plays it as an animated
 * "xmr-txsigned" UR so the output chain can be exercised before the full
 * scan -> detail -> sign -> result flow is assembled.
 */
#ifndef SHLOSILO_DEMO_PAYLOAD_H
#define SHLOSILO_DEMO_PAYLOAD_H

#include <stdint.h>

#define DEMO_PAYLOAD_TYPE "xmr-txsigned"
#define DEMO_PAYLOAD_LEN  {len(data)}

static const uint8_t g_demo_payload[DEMO_PAYLOAD_LEN] = {{
{body}
}};

#endif
"""

OUT.write_text(text, encoding="utf-8", newline="\n")
print(f"wrote {OUT.relative_to(REPO)} ({len(data)} bytes, sha256 {digest})")
