#!/usr/bin/env python3
"""Generate the FFI keep table for the forgebox staticlib shim.

Why: the shim bundles the core crate into a staticlib. Under LTO, a staticlib
only retains what is *reachable*; `extern "C"` declarations + a #[used] table do
NOT make the core's functions reachable (verified: they come out `U`/undefined),
while a real Rust-path reference does (they come out `T`/defined). So every
entry point must be referenced through its actual Rust path.

Run:  python3 scripts/gen_ffi_keep.py           # rewrite the block
      python3 scripts/gen_ffi_keep.py --check   # exit 1 if stale
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SHIM = REPO / "flux/forgebox/staticlib/src/lib.rs"
FORMS = REPO / "forms"
MARKER_START = "// ── C-ABI keep-table (generated by scripts/gen_ffi_keep.py) ──"

FUNC_RE = re.compile(r'^\s*pub (?:unsafe )?extern "C" fn (shlosilo_[a-z_0-9]+)')
MOD_HEAD_RE = re.compile(r"\bmod\s+([A-Za-z_][A-Za-z_0-9]*)\s*$")
ATTR_RE = re.compile(r"^\s*#\[(.*)\]")
CFG_IN_ATTR_RE = re.compile(r"^cfg\((.+)\)$")


def module_path(rel: Path) -> str:
    """forms/ffi/version.rs -> shlosilo::ffi::version ; forms/device_timing.rs -> shlosilo::device_timing"""
    parts = list(rel.with_suffix("").parts)
    if parts and parts[-1] == "mod":
        parts = parts[:-1]
    if not parts:
        return "shlosilo"
    return "shlosilo::" + "::".join(parts)


def strip_strings_and_comments(line: str) -> str:
    """Blank out //-comments and string/char literals so brace counting is safe."""
    out = []
    i, n = 0, len(line)
    while i < n:
        c = line[i]
        if c == "/" and i + 1 < n and line[i + 1] == "/":
            break
        if c == '"':
            j = i + 1
            while j < n:
                if line[j] == "\\":
                    j += 2
                    continue
                if line[j] == '"':
                    break
                j += 1
            i = j + 1
            out.append(" ")
            continue
        if c == "'":  # char literal or lifetime; blank short char literals only
            if i + 2 < n and line[i + 2] == "'":
                i += 3
                out.append(" ")
                continue
            out.append(c)
            i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


def collect():
    entries = []
    for path in sorted(FORMS.rglob("*.rs")):
        rel = path.relative_to(FORMS)
        lines = path.read_text().splitlines()
        base = module_path(rel)
        # stack of (is_mod, name) for currently open blocks
        stack = []
        stmt = ""  # statement text since the last brace/semicolon boundary
        for i, raw in enumerate(lines):
            line = strip_strings_and_comments(raw)
            m = FUNC_RE.match(raw)  # match on the raw line: stripping blanks "C" in extern "C"
            if m:
                name = m.group(1)
                mods = [nm for is_mod, nm in stack if is_mod]
                full_mod = base + ("::" + "::".join(mods) if mods else "")
                # walk back for attributes (blank/comment/attr lines)
                attrs = []
                j = i - 1
                while j >= 0:
                    s = lines[j].strip()
                    if s == "" or s.startswith("//"):
                        j -= 1
                        continue
                    am = ATTR_RE.match(s)
                    if am:
                        attrs.append(am.group(1))
                        j -= 1
                        continue
                    break
                cfg = None
                for a in attrs:
                    cm = CFG_IN_ATTR_RE.match(a)
                    if cm:
                        cfg = cm.group(1)
                if not (cfg and "test" in cfg):
                    entries.append((name, full_mod, cfg))
            # update the block stack for this line
            for c in line:
                if c == "{":
                    mm = MOD_HEAD_RE.search(stmt)
                    if mm:
                        stack.append((True, mm.group(1)))
                    else:
                        stack.append((False, None))
                    stmt = ""
                elif c == "}":
                    if stack:
                        stack.pop()
                    stmt = ""
                elif c == ";":
                    stmt = ""
                else:
                    if len(stmt) < 100:
                        stmt += c
    return entries


def render(entries):
    out = [MARKER_START]
    out.append("// Every entry point is referenced via its real Rust path so LTO")
    out.append("// cannot drop it from the bundled staticlib (extern decls do not")
    out.append("// create reachability; they left every symbol undefined).")
    out.append("")
    out.append("#[repr(transparent)]")
    out.append("struct Addr(*const ());")
    out.append("// SAFETY: the table is immutable and holds only code addresses.")
    out.append("unsafe impl Sync for Addr {}")
    out.append("")
    cfg_groups = {}
    for name, mod, cfg in entries:
        cfg_groups.setdefault(cfg, []).append((name, mod))
    out.append("#[used]")
    out.append(f"static KEEP_FFI: [Addr; {len(entries)}] = [")
    for cfg in sorted(cfg_groups, key=lambda c: (c is not None, c or "")):
        group = cfg_groups[cfg]
        if cfg:
            out.append(f"    #[cfg({cfg})]")
        for name, mod in group:
            out.append(f"    Addr({mod}::{name} as *const ()),")
    out.append("];")
    out.append("")
    return "\n".join(out)


def main():
    entries = collect()
    block = render(entries)
    text = SHIM.read_text()
    if MARKER_START in text:
        head = text[: text.index(MARKER_START)].rstrip() + "\n\n"
    else:
        head = text.rstrip() + "\n\n"
        head = re.sub(r"\n// ── C-ABI keep-table ──\n.*\Z", "\n", head, flags=re.S)
        head = re.sub(r"\n#\[used\]\nstatic KEEP_FFI.*\Z", "\n", head, flags=re.S)
        head = re.sub(r'\nextern "C" \{\n(?:    fn shlosilo_[a-z_0-9]+\(\);\n)+\}\n', "\n", head)
    new = head + block
    if "--check" in sys.argv:
        if new != text:
            print("FAIL: shim keep-table is stale; run scripts/gen_ffi_keep.py")
            sys.exit(1)
        print("OK: keep-table up to date (%d entries)" % len(entries))
        return
    SHIM.write_text(new)
    print("wrote %d entries:" % len(entries))
    for name, mod, cfg in entries:
        print(f"  {name:32s} {mod}" + (f"  [cfg({cfg})]" if cfg else ""))


if __name__ == "__main__":
    main()
