//! C-host runtime + staticlib bundle for the forgebox appearance.
//!
//! This crate is what turns the shlosilo `forms` core into `libshlosilo.a`
//! for the C host, and it owns everything the C host must provide:
//! - global allocator (FreeRTOS heap via `shlosilo_embedded_malloc/free`)
//! - panic handler (LCD display via `shlosilo_panic_hook`)
//! - critical-section impl (PRIMASK interrupt masking; ForgeBox is single-core)
//!
//! The core crate is a plain rlib and knows nothing about this host. The
//! staticlib is requested here - and only here - so no other consumer of the
//! core (e.g. a Rust-native appearance such as flux/pico2) is ever forced
//! through a staticlib unit or these runtime hooks.

#![no_std]

use core::alloc::{GlobalAlloc, Layout};
use core::fmt::Write as _;
use core::panic::PanicInfo;

use critical_section::RawRestoreState;

extern "C" {
    /// Provided by the forgebox firmware: FreeRTOS pvPortMalloc wrapper
    fn shlosilo_embedded_malloc(size: usize) -> *mut u8;
    /// Provided by the forgebox firmware: vPortFree wrapper
    fn shlosilo_embedded_free(ptr: *mut u8);
}

pub struct EmbeddedAllocator;

unsafe impl GlobalAlloc for EmbeddedAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        shlosilo_embedded_malloc(layout.size())
    }
    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
        shlosilo_embedded_free(ptr)
    }
}

#[global_allocator]
static EMBEDDED_ALLOCATOR: EmbeddedAllocator = EmbeddedAllocator;

// ── critical-section impl (PRIMASK interrupt masking) ──
// RawRestoreState is u8 (restore-state-u8 in Cargo.toml, aligned with
// embassy-rp's critical-section-impl): 1 = IRQs were enabled before acquire.
struct SingleCoreInterrupts;

unsafe impl critical_section::Impl for SingleCoreInterrupts {
    unsafe fn acquire() -> RawRestoreState {
        let mut primask: u32;
        core::arch::asm!(
            "mrs {0}, primask",
            "cpsid i",
            out(reg) primask,
            options(nomem, nostack, preserves_flags)
        );
        (primask & 1) as u8
    }

    unsafe fn release(restore_state: RawRestoreState) {
        if restore_state != 0 {
            core::arch::asm!("msr primask, {0}", in(reg) 1u32, options(nomem, nostack, preserves_flags));
        } else {
            core::arch::asm!("cpsie i", options(nomem, nostack, preserves_flags));
        }
    }
}

critical_section::set_impl!(SingleCoreInterrupts);

#[panic_handler]
fn shlosilo_panic(info: &PanicInfo) -> ! {
    // collect the panic message into a stack buffer and hand it to the C-side hook to display on the LCD (no serial port on device)
    let mut buf = [0u8; 160];
    let pos;
    {
        let mut w = PanicWriter {
            buf: &mut buf,
            pos: 0,
        };
        if let Some(msg_str) = info.message().as_str() {
            let _ = w.write_str(msg_str);
        } else {
            let _ = w.write_str("panic");
        }
        if let Some(loc) = info.location() {
            let _ = core::fmt::write(
                &mut w,
                core::format_args!(" @ {}:{}", loc.file(), loc.line()),
            );
        }
        pos = w.pos;
    } // w dropped, buf borrow ends
      // contract: the hook returns ! (LCD display + infinite loop keeps the system alive) and never returns
    unsafe {
        shlosilo_panic_hook(buf.as_ptr(), pos);
    }
}

struct PanicWriter<'a> {
    buf: &'a mut [u8],
    pos: usize,
}

impl core::fmt::Write for PanicWriter<'_> {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        let n = core::cmp::min(s.len(), self.buf.len() - self.pos);
        self.buf[self.pos..self.pos + n].copy_from_slice(&s.as_bytes()[..n]);
        self.pos += n;
        Ok(())
    }
}

extern "C" {
    /// Provided by the forgebox firmware: display panic info (LCD) + keep the system alive/refresh
    fn shlosilo_panic_hook(msg: *const u8, len: usize) -> !;
}

// ── C-ABI keep-table (generated by scripts/gen_ffi_keep.py) ──
// Every entry point is referenced via its real Rust path so LTO
// cannot drop it from the bundled staticlib (extern decls do not
// create reachability; they left every symbol undefined).

#[repr(transparent)]
struct Addr(*const ());
// SAFETY: the table is immutable and holds only code addresses.
unsafe impl Sync for Addr {}

#[used]
static KEEP_FFI: [Addr; 50] = [
    Addr(shlosilo::device_timing::shlosilo_timing_set_clock_fn as *const ()),
    Addr(shlosilo::device_timing::shlosilo_timing_get_stage as *const ()),
    Addr(shlosilo::device_timing::shlosilo_timing_get_total as *const ()),
    Addr(shlosilo::device_timing::shlosilo_timing_reset as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_sign_ffi as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_sign_ws_len as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_ur_encode_ws_len as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_ur_decode_ws_len as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_sign_ur_ffi as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_export_readonly_ffi as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_create_account_ffi as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_supported_networks_ffi as *const ()),
    Addr(shlosilo::ffi::c_abi::shlosilo_supported_protocols_ffi as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_encode_begin as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_encode_next as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_encode_next_cyclic as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_encode_free as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_decode_new as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_decode_feed as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_decode_progress as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_decode_complete as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_decode_payload as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_decode_type as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_sign_typed_ffi as *const ()),
    Addr(shlosilo::ffi::c_abi::r3::shlosilo_ur_decode_free as *const ()),
    Addr(shlosilo::ffi::cn_timing_ffi::shlosilo_cn_timing_set_clock as *const ()),
    Addr(shlosilo::ffi::cn_timing_ffi::shlosilo_cn_timing_reset as *const ()),
    Addr(shlosilo::ffi::cn_timing_ffi::shlosilo_cn_timing_phase as *const ()),
    Addr(shlosilo::ffi::generator_cache_ffi::shlosilo_gen_cache_set_hooks as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_fmul as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_fsq as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_select as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_madd as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_quadruple as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_ct_chunk as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_vartime_2term as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_select_affine as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_madd_affine as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_ct_chunked as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_vartime_2term_fw as *const ()),
    Addr(shlosilo::ffi::perf_bench_ffi::shlosilo_perf_xchain as *const ()),
    Addr(shlosilo::ffi::prove_timing_ffi::shlosilo_bp_timing_set_clock as *const ()),
    Addr(shlosilo::ffi::prove_timing_ffi::shlosilo_bp_timing_reset as *const ()),
    Addr(shlosilo::ffi::prove_timing_ffi::shlosilo_bp_timing_phase as *const ()),
    Addr(shlosilo::ffi::tx_phase_ffi::shlosilo_tx_phase_set_clock as *const ()),
    Addr(shlosilo::ffi::tx_phase_ffi::shlosilo_tx_phase_reset as *const ()),
    Addr(shlosilo::ffi::tx_phase_ffi::shlosilo_tx_phase_phase as *const ()),
    Addr(shlosilo::ffi::version::shlosilo_version as *const ()),
    Addr(shlosilo::ffi::version::shlosilo_cabi_version as *const ()),
    Addr(shlosilo::ffi::version::shlosilo_cabi_check as *const ()),
];
